Introduce Landmines
MT-CTF/capturetheflag pull request #1001
Opened 2022-04-24 19:22 UTC by xenonca

2022-04-26 17:57 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_traps.lua
> +			local plyrs = minetest.get_objects_inside_radius(pos, 3)
`get_objects_inside_x()` picks up all objects, not just players, for landmine activation that might be intended (at the cost of faster code?) but you never check this for `plyrs`

2022-04-26 17:57 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_traps.lua
> +				texture = "grenades_boom.png",
Would probably be a good idea to add `grenades` as a dependency

2022-04-26 17:57 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_traps.lua
> +	min_y = -3000,
```suggestion
	min_y = 0,
```
I don't think maps are placed below y=0

2022-04-27 09:37 UTC, xenonca commented on mods/ctf/ctf_map/ctf_traps.lua
> +			local plyrs = minetest.get_objects_inside_radius(pos, 3)
Do you think it would be better if only players could trigger the landmine? Just keep in mind that would disallow activation when a player wants to trigger it by throwing an item on it, for example.

2022-04-30 13:40 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_traps.lua
> +			local plyrs = minetest.get_objects_inside_radius(pos, 3)
Considering how expensive it is to make it might be best to prevent enemies from being able to disable it

2022-05-09 22:32 UTC, savilli requested changes

2022-05-09 22:32 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +	min_y = 0,
You can just not set `min_y` and `max_y`. It doesn't make a difference since CTF doesn't have chunks there.

2022-05-09 22:32 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +		local objs = minetest.get_objects_in_area({x=pos.x-0.5, y=pos.y-0.5, z=pos.z-0.5},
Why do you need to call `get_objects_in_area` and `get_objects_inside_radius` after? I think one call is enough.

2022-05-09 22:32 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +			for _, v in pairs(plyrs) do
Landmines shouldn't be able to damage your teammates. Probably, shouldn't be activated by them at all.

2022-05-09 22:32 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +		meta:set_string("placer", minetest.serialize({
You don't need to save the player's team, the name is enough. Look at https://github.com/MT-CTF/capturetheflag/blob/65425850b9cf84fe52bf090e2d115d028f6237c0/mods/ctf/ctf_map/ctf_traps.lua#L90 and https://github.com/MT-CTF/capturetheflag/blob/65425850b9cf84fe52bf090e2d115d028f6237c0/mods/ctf/ctf_map/ctf_traps.lua#L53.

2022-05-09 22:32 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +					v:punch(placer_obj, 1, {damage_groups = {fleshy = 10}}, nil)
You need to add a new damage_group, or there will be a wrong icon in the kill list. Look at https://github.com/MT-CTF/capturetheflag/blob/65425850b9cf84fe52bf090e2d115d028f6237c0/mods/ctf/ctf_map/ctf_traps.lua#L61 and https://github.com/MT-CTF/capturetheflag/blob/092a8025a2a37b71817c6cd733fe9b98982612bc/mods/ctf/ctf_modebase/features.lua#L16.

2022-07-19 20:18 UTC, xenonca commented on mods/ctf/ctf_map/ctf_traps.lua
> +		local objs = minetest.get_objects_in_area({x=pos.x-0.5, y=pos.y-0.5, z=pos.z-0.5},
The first call (`get_objects_in_area`) is to determine wether the landmine has been triggered or not cause `get_objects_inside_radius` is too inaccurate. The second call is to determine the radius in which players get damaged.

2022-08-03 12:12 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +		meta:set_string("placer", minetest.serialize({
You don't need to serialize one string, just `meta:set_string("placer", name)`

2022-08-03 12:15 UTC, savilli commented on mods/ctf/ctf_map/ctf_traps.lua
> +		local objs = minetest.get_objects_in_area({x=pos.x-0.5, y=pos.y-0.5, z=pos.z-0.5},
Did you try to use `get_objects_inside_radius` call and did you notice the difference? I didn't notice it by myself.

2022-08-03 12:22 UTC, savilli reviewed
I'm not sure how useful landmines will be. For me they feel slow, and an enemy can easily run over them. I think we should test them with more people and get their feedback.

2022-08-08 18:12 UTC, xenonca commented on mods/ctf/ctf_map/ctf_traps.lua
> +		local objs = minetest.get_objects_in_area({x=pos.x-0.5, y=pos.y-0.5, z=pos.z-0.5},
I did try it. The landmine is triggered when you're standing on the neighbouring half of a neighbouring node. If using 0.5 it isn't triggered when standing on the corner of the landmine. And that on the other hand would be a too small radius for players to be damaged in.

2022-08-11 18:59 UTC, LoneWolfHT commented
Merge conflicts need resolving

2022-08-13 08:15 UTC, magnetar47 commented
@xenonca Please add a description to the PR, explaining how the landmines work, how to craft, how to place, the damage caused, and other stuff we should take note of. Thanks.

2022-08-14 11:11 UTC, xenonca commented
> I'm not sure how useful landmines will be. For me they feel slow, and an enemy can easily run over them. I think we should test them with more people and get their feedback.

If nobody objects I'll go ahead and ping Testers on Discord for this purpose

2022-08-14 11:26 UTC, magnetar47 commented
> > I'm not sure how useful landmines will be. For me they feel slow, and an enemy can easily run over them. I think we should test them with more people and get their feedback.
> 
> If nobody objects I'll go ahead and ping Testers on Discord for this purpose

Let's start the testing phase. 👍

2022-08-17 13:27 UTC, Lucyucy reviewed
To compensate for the long reaction time I'd suggest a more discreet design/smaller size

2022-08-19 10:33 UTC, LuismiInTheZone commented
Emm, when I enter into the game and try to test it the game kick me so... I can't test it if first thing I see is how it kick me

2022-08-19 11:12 UTC, magnetar47 commented
> Emm, when I enter into the game and try to test it the game kick me so... I can't test it if first thing I see is how it kicks me

Posting the reason that got you "kicked" would be useful in solving your problem.

2022-08-19 12:31 UTC, LuismiInTheZone commented
> > Emm, when I enter into the game and try to test it the game kick me so... I can't test it if first thing I see is how it kicks me
> 
> Posting the reason that got you "kicked" would be useful in solving your problem.

I went to get on the landmine and it kicked me

2022-08-19 17:38 UTC, magnetar47 commented
> > > Emm, when I enter into the game and try to test it the game kick me so... I can't test it if first thing I see is how it kicks me
> > 
> > 
> > Posting the reason that got you "kicked" would be useful in solving your problem.
> 
> I went to get on the landmine and it kicked me

Kicked you as in kicked you from the game? What's the message you got?

2022-08-19 22:17 UTC, xenonca commented
I think I konw what that might have been, @Lucyucy pointed out a bug to me a few days ago, I'll try to fix it soon.

2022-09-11 13:51 UTC, farooqkz commented
> 

Just like Spikes. The problems that it checks every X second rather than having an event which triggers when the player gets to a certain distance.

But I think Landmines will be better than Spikes. At least no friendly damage.

2022-09-11 13:53 UTC, farooqkz commented
> I think I know what that might have been, @Lucyucy pointed out a bug to me a few days ago, I'll try to fix it soon.

Has it been fixed? I would really like to see landmines IG and I tried to help but it seems @xenonca doesn't want to accept help and do the job all themselves.

2022-09-29 18:48 UTC, xenonca commented
@farooqkz your reasoning is untrue. I rejected your PRs because they did not solve the mentioned issues and the damage/trigger calculation was too inaccurate (as I explained [here](https://github.com/xenonca/capturetheflag/pull/1#issuecomment-1192499364)), not because I don't want to accept any help. I'll update the PR when I have the time to implement the fix in my fork.
The PR has a WIP label for a reason.

2022-12-04 02:25 UTC, LoneWolfHT commented
* There seems to still be debug stuff in the chat ![image](https://user-images.githubusercontent.com/28972859/205470947-dac09712-0c64-49f6-b3c9-61b56774d032.png)

* Since you can place landmines in enemy territory it might be a good idea to color-code them to teams. This should be possible using a mask and [multiply

2022-12-07 21:48 UTC, pl608 commented
I made a pr with a different method of checking for players. Still testing locally.

2023-02-07 10:45 UTC, farooqkz commented
Github has the Draft PR feature. So I think it's a good idea to remove the label and make this PR a draft.

2023-02-07 10:47 UTC, farooqkz commented
> * There seems to still be debug stuff in the chat ![image](https://user-images.githubusercontent.com/28972859/205470947-dac09712-0c64-49f6-b3c9-61b56774d032.png)
> 
>     * Since you can place landmines in enemy territory it might be a good idea to color-code them to teams. This should be possible using a mask and [multiply

I would like to fix these stuff on the behalf of @xenonca. Is that possible?

2023-02-07 10:49 UTC, farooqkz commented on mods/ctf/ctf_map/ctf_traps.lua
> +		meta:set_string("placer", name)
Now people can change teams during a match. So I think it is a good idea to store placer's team as well.

2023-02-08 05:42 UTC, LoneWolfHT commented
> I would like to fix these stuff on the behalf of @xenonca. Is that possible?

You could do a code change suggestion in a review

2023-02-08 12:02 UTC, farooqkz commented
> > I would like to fix these stuff on the behalf of @xenonca. Is that possible?
> 
> You could do a code change suggestion in a review

Yeah but I want landmines in game and it is taking too long for Xenon to progress.

2023-02-09 21:16 UTC, LoneWolfHT commented
I guess you can see what @xenonca has to say

2023-02-11 17:55 UTC, xenonca commented
Hey, I'm aware that this PR is advancing extremely slowly. I'm currently quite busy with RL stuff which is keeping me from finishing this. I'm sorry that the landmines PR isn't progressing at the pace you'd wish it would.
If you don't mind, I would still like to work on the PR as I initiated the idea. Help in the form of code reviews/suggestions is always welcome though.

2023-02-11 18:43 UTC, farooqkz commented
> 

All of us are busy with real life stuff and this project is a hobby of us. So not contributing for a while or even longer is natural. Since my early days of CTF(as a player mostly), there are many who have come and gone. As an obvious example rubenwardy is long gone and LV/LW has replaced him.

Now regarding your idea and contribution, I would really love to see this thing in game. If you don't agree with someone else continuing your work, then I won't interfere except for suggestions and code reviews. But I humbly ask you to let someone else continue this. The progress is not complicated, someone will fork your fork, make required changes and then merge it into this repo. The commits which were yours are still yours. Some new commits will include this though.

2023-02-25 20:27 UTC, xenonca commented
Look, I'm not a dev and have barely some programming skills. :P
I've surprisingly come up with a good idea that I believe would add to the gameplay and so I'd like to be the one who gets it done too. There are like a ton of other things that need to be done for CTF and you're free to come up with your own ideas at any time or contribute to existing PRs (in the form of suggestions/reviews). I don't quite understand why you want to _adopt_ this specific PR so much, more than anything else.
> ...it is taking too long...

I'm aware of that, but players in game aren't even really aware of the PR really so I don't see a real reason to rush here. I think the day it gets added to the game will be the same for the players any time, no matter if that'll happen tomorrow, in 2 weeks or in a month.
As I've already said, I would still like to continue this PR, however, there will be nothing stopping you from opening your own PR.

2023-02-25 20:31 UTC, xenonca commented
> * There seems to still be debug stuff in the chat ![image](https://user-images.githubusercontent.com/28972859/205470947-dac09712-0c64-49f6-b3c9-61b56774d032.png)
> 
>     * Since you can place landmines in enemy territory it might be a good idea to color-code them to teams. This should be possible using a mask and [multiply

Debug should be gone now. I'm wondering what would be the best solution. Add team masks or limit the placement of landmines to the team's territory. That would also add a little risk (in a positive way?) when stepping on it, similar to how damage cobble works.

2023-02-25 20:32 UTC, xenonca commented on mods/ctf/ctf_map/ctf_traps.lua
> +		meta:set_string("placer", name)
Should be fixed now

2023-02-25 20:45 UTC, farooqkz commented
> Look, I'm not a dev and have barely some programming skills. :P I've surprisingly come up with a good idea that I believe would add to the gameplay and so I'd like to be the one who gets it done too. There are like a ton of other things that need to be done for CTF and you're free to come up with your own ideas at any time or contribute to existing PRs (in the form of suggestions/reviews). I don't quite understand why you want to _adopt_ this specific PR so much, more than anything else.
> 
> > ...it is taking too long...
> 
> I'm aware of that, but players in game aren't even really aware of the PR really so I don't see a real reason to rush here. I think the day it gets added to the game will be the same for the players any time, no matter if that'll happen tomorrow, in 2 weeks or in a month. As I've already said, I would still like to continue this PR, however, there will be nothing stopping you from opening your own PR.

The problems that I'm both a player here and a code contributor. As a player, I would love to see landmines in game. And as a programmer, when I see you are just one epsilon away from finishing your work, while I can do it in a trivial time to finally see it in game, I have a lust to finish your work and finally have it in game. It'll be still your work plus a little bit help from me.

The idea of landmine was proposed in the early days of CTF in #35 and much later I, unknowingly, made a duplicate(#150).

P.S.: Coming up with good ideas for gameplay is one thing and implementing it is another thing. One might come up with very good ideas but with no programming skills. And someone like me would come with several bad ideas but with strong programming background. For a list of them you can see my messages in the related channel in Discord. And the issues I opened in this repo in the days of rubenwardy :)

2023-03-01 08:41 UTC, farooqkz commented
@LoneWolfHT I believe I don't have permission to suggest changes. Or that I am overlooking something.

2023-03-02 17:11 UTC, LoneWolfHT commented
> @LoneWolfHT I believe I don't have permission to suggest changes. Or that I am overlooking something.

![image](https://user-images.githubusercontent.com/28972859/222501753-995c9f04-e27b-4500-bb38-4f8a81e2e3a2.png)

Click that and then edit the code that appears in your comment box

2023-03-17 16:39 UTC, farooqkz commented
@LoneWolfHT How long should before someone else could take the job by forking Xenon's fork, making changes and creating a PR to this repo.

2023-03-23 20:30 UTC, LoneWolfHT commented
> @LoneWolfHT How long should before someone else could take the job by forking Xenon's fork, making changes and creating a PR to this repo?

Wait until they agree it'll take to long for them to finish it themselves

2023-03-23 22:40 UTC, xenonca commented
JFYI, I never claimed to be the first one suggesting this idea, but apparently the one who actually started the PR for it.  
I feel like I had already clarified my point in my last message: I do want to finish this myself, even if it will take me longer than it would probably take you. However, there won't be anything stopping you from opening your own PR if you insist. The way you urge me to finish this PR instead of contributing by making useful suggestions is getting annoying and honestly makes me feel uncomfortable. I'm wasting more time and resources into this discussion and repeateing myself than into the actual PR.

2023-03-24 10:11 UTC, farooqkz commented
I'm sorry @xenonca if you've made uncomfortable. It seems I am rushing way too much. I've made some suggestions. I hope they will be useful :)

2023-03-25 06:18 UTC, tigercoding56 commented
> * There seems to still be debug stuff in the chat ![image](https://user-images.githubusercontent.com/28972859/205470947-dac09712-0c64-49f6-b3c9-61b56774d032.png)
> 
>     * Since you can place landmines in enemy territory it might be a good idea to color-code them to teams. This should be possible using a mask and [multiply

honestly i wish you could place whatever you like in enemy territory

2023-05-24 20:09 UTC, farooqkz commented
I agree with @xenonca and @tigercoding56 regarding their points. I also believe they must explode on punch or when trying to dig if they are not own landmines.

I have another idea which I am unsure if it's good: chain explode. That explosion of a landmine causes neighbor landmines to explode as well. However, with the current configuration I'd say we'll have too few for this idea.

2023-06-11 18:21 UTC, LoneWolfHT commented
> > honestly i wish you could place whatever you like in enemy territory
> 
> I feel so too. Actually I believe that texture masks indicating the team color do not really make sense either. Because where's the point of having landmines if you already know in beforehand whether they'll blow you up or not. Considering that they are very rare in team chests and pretty hard to craft I'd go with not adding either of it and see how it works in-game first.

Ok, that sounds good

2023-07-28 08:07 UTC, farooqkz commented
@LoneWolfHT IMO, my suggestions should be committed before merge.

2023-07-30 02:45 UTC, LoneWolfHT commented
> @LoneWolfHT IMO, my suggestions should be committed before merge.

That's up to Xenon

2023-07-30 03:01 UTC, LoneWolfHT commented
On switching this from an ABM to a globalstep (braindump):

* Track the positions of all placed landmines in a table (`table[minetest.pos_to_string(vector.round(pos))] = <placer's team>` or something)
* Set up a globalstep that runs every 0.5 seconds. The following indented points should be inside this globalstep:
  * Create a `playerref` table of the style `{pname = {pteam = player:get_player_name(), pos = player:get_pos()}, ...}` filled with all online players in a team
  * Loop over your table of landmines, and compare their positions/owning-teams with the players stored in your `playerref` table. Explode if they're close enough, maybe looping over your `playerref` table and comparing positions a second time to find nearby players to hit.
* Remember to remove landmine positions from your landmines table in the landmine node's `on_destruct()`. Make sure the key (landmine position) you use to do that is rounded and converted to string form
* Completely empty your landmine table in a `ctf_api.register_on_match_end()`

2024-06-11 14:45 UTC, farooqkz commented
@LoneWolfHT This is ready for another review and finally merging. The low value of globalstep threshold is because otherwise people could run over landmine undetected.

2024-11-01 11:52 UTC, mrtechtroid commented
@farooqkz @LoneWolfHT Merge?

2024-11-01 14:19 UTC, farooqkz commented
Last time I checked there isn't anything preventing it from being merged. Tho I can't say if there are recent changes in CTF conflicting with it. And the merge is up to someone with push access anyway.

2024-11-02 00:21 UTC, LoneWolfHT commented
> On switching this from an ABM to a globalstep (braindump):
> 
> * Track the positions of all placed landmines in a table (`table[minetest.pos_to_string(vector.round(pos))] = <placer's team>` or something)
> * Set up a globalstep that runs every 0.5 seconds. The following indented points should be inside this globalstep:
>   * Create a `playerref` table of the style `{pname = {pteam = player:get_player_name(), pos = player:get_pos()}, ...}` filled with all online players in a team
>   * Loop over your table of landmines, and compare their positions/owning-teams with the players stored in your `playerref` table. Explode if they're close enough, maybe looping over your `playerref` table and comparing positions a second time to find nearby players to hit.
> * Remember to remove landmine positions from your landmines table in the landmine node's `on_destruct()`. Make sure the key (landmine position) you use to do that is rounded and converted to string form
> * Completely empty your landmine table in a `ctf_api.register_on_match_end()`
>   
>   

Something still needs to be done about this

2024-11-02 02:48 UTC, pl608 commented
I havent been paying much attention but arent landmines dps based and
explosion effects is triggered from on_player_damage (or whatever the
function is called)

On Fri, Nov 1, 2024 at 5:22 PM LoneWolfHT ***@***.***> wrote:

> On switching this from an ABM to a globalstep (braindump):
>
>    - Track the positions of all placed landmines in a table (table[minetest.pos_to_string(vector.round(pos))]
>    = <placer's team> or something)
>    - Set up a globalstep that runs every 0.5 seconds. The following
>    indented points should be inside this globalstep:
>       - Create a playerref table of the style {pname = {pteam =
>       player:get_player_name(), pos = player:get_pos()}, ...} filled with
>       all online players in a team
>       - Loop over your table of landmines, and compare their
>       positions/owning-teams with the players stored in your playerref
>       table. Explode if they're close enough, maybe looping over your
>       playerref table and comparing positions a second time to find
>       nearby players to hit.
>    - Remember to remove landmine positions from your landmines table in
>    the landmine node's on_destruct(). Make sure the key (landmine
>    position) you use to do that is rounded and converted to string form
>    - Completely empty your landmine table in a
>    ctf_api.register_on_match_end()
>
> Something still needs to be done about this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MT-CTF/capturetheflag/pull/1001#issuecomment-2452749123>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASWE3NPBH5GBFOZU4XPY3V3Z6QLKZAVCNFSM6AAAAABJEKESA2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJSG42DSMJSGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-02 11:26 UTC, farooqkz commented
> > On switching this from an ABM to a globalstep (braindump):
> > 
> > * Track the positions of all placed landmines in a table (`table[minetest.pos_to_string(vector.round(pos))] = <placer's team>` or something)
> > * Set up a globalstep that runs every 0.5 seconds. The following indented points should be inside this globalstep:
> >   
> >   * Create a `playerref` table of the style `{pname = {pteam = player:get_player_name(), pos = player:get_pos()}, ...}` filled with all online players in a team
> >   * Loop over your table of landmines, and compare their positions/owning-teams with the players stored in your `playerref` table. Explode if they're close enough, maybe looping over your `playerref` table and comparing positions a second time to find nearby players to hit.
> > * Remember to remove landmine positions from your landmines table in the landmine node's `on_destruct()`. Make sure the key (landmine position) you use to do that is rounded and converted to string form
> > * Completely empty your landmine table in a `ctf_api.register_on_match_end()`
> 
> Something still needs to be done about this

As far as I remember I did this. so better check the code.

2024-11-10 23:00 UTC, LoneWolfHT requested changes

2024-11-10 23:00 UTC, LoneWolfHT commented on mods/ctf/ctf_map/maps
map submodule change was committed, this should be undone

2024-11-10 23:00 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/crafting.lua
> +})
Missing a newline at the end of the file

2024-12-01 21:00 UTC, LoneWolfHT requested changes

2024-12-01 21:00 UTC, LoneWolfHT commented on mods/ctf/ctf_map/maps
PR not mergable, you edited/didn't update the maps submodule and committed that to your PR

2024-12-02 17:14 UTC, farooqkz commented
Before merge, there is a bug here. See the kill log:

![screenshot_20241202_204321](https://github.com/user-attachments/assets/69d81a4c-72b9-4dea-b49c-e24391f5101e)

2024-12-02 17:18 UTC, farooqkz commented
> Before merge, there is a bug here. See the kill log:
> 
> ![screenshot_20241202_204321](https://private-user-images.githubusercontent.com/15038218/391646363-69d81a4c-72b9-4dea-b49c-e24391f5101e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNjAxMzAsIm5iZiI6MTczMzE1OTgzMCwicGF0aCI6Ii8xNTAzODIxOC8zOTE2NDYzNjMtNjlkODFhNGMtNzJiOS00ZGVhLWI0OWMtZTI0MzkxZjUxMDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE3MTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYWJiNDgzMDRkNGIwZjI5ZTY5ZjhhM2Y4MDc1ZjdkYzI4NDBhMWI0MmY1NzhiMzIxZWFlNzkwZGFhMGJlMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NdRTg8UszGjhCPWr3le1bktBrRwC8yTVptIuXnKQ5d8)
> 
> Edit: nevermind I didn't see the error.

fixed

2024-12-02 20:08 UTC, merged