Fix #984
MT-CTF/capturetheflag pull request #1022
Opened 2022-07-24 11:37 UTC by farooqkz

Screenshots attached
![screenshot_20220724_160155](https://user-images.githubusercontent.com/15038218/180645143-285074d4-6888-4e47-8f2f-85adfb21802f.png)
![screenshot_20220724_160255](https://user-images.githubusercontent.com/15038218/180645147-aea04f74-6a94-4d0a-b191-ce13b0476884.png)

2022-07-29 03:54 UTC, LoneWolfHT commented
Please disable texturepacks when showing texture changes
![image](https://user-images.githubusercontent.com/28972859/181679446-06566fbc-db1f-4fc3-8dcb-a25e98ec6d6c.png)

2022-07-29 03:56 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_traps.lua
> +	end
What is this bit for?

2022-07-29 20:42 UTC, farooqkz commented on mods/ctf/ctf_map/ctf_traps.lua
> +	end
oh sorry it shouldn't be there

2022-07-29 20:46 UTC, farooqkz commented
> Please disable texturepacks when showing texture changes ![image](https://user-images.githubusercontent.com/28972859/181679446-06566fbc-db1f-4fc3-8dcb-a25e98ec6d6c.png)

why? isn't the point of `[colorize` is making it less obvious for users of texture packs?

2022-08-11 17:50 UTC, LoneWolfHT commented
> > Please disable texturepacks when showing texture changes ![image](https://user-images.githubusercontent.com/28972859/181679446-06566fbc-db1f-4fc3-8dcb-a25e98ec6d6c.png)
> 
> why? isn't the point of `[colorize` is making it less obvious for users of texture packs?

You can do both if you want, but I have no idea what I'm looking at with non-default textures

2022-08-11 17:54 UTC, LoneWolfHT requested changes
Please change the unwalkable node [colorize overlays to yellow (to match color of the current textures) and revert the changes to the damage cobble, we'll leave that obvious for now

2022-09-11 13:23 UTC, farooqkz commented
> Please change the unwalkable node [colorize overlays to yellow (to match color of the current textures) and revert the changes to the damage cobble, we'll leave that obvious for now

Done. Screenshot attached.
![Uploading screenshot_20220911_174919.png…]()

2022-09-22 15:40 UTC, LoneWolfHT approved these changes

2022-09-22 16:18 UTC, merged