Fix #1028
MT-CTF/capturetheflag pull request #1029
Opened 2022-07-30 19:03 UTC by farooqkz

Smoke grenade hiss sound was locationless because the ogg file was not mono.
Fixed in this PR.

2022-08-03 11:36 UTC, savilli commented
LGTM

2022-08-03 20:19 UTC, LoneWolfHT requested changes
The glasslike break sound isn't mono either

2022-08-04 10:45 UTC, farooqkz commented
> The glasslike break sound isn't mono either

done

2022-08-04 12:36 UTC, LoneWolfHT approved these changes

2022-08-04 12:37 UTC, merged