Replace the sender-side response for /msg
MT-CTF/capturetheflag pull request #1048
Opened 2022-08-25 12:43 UTC by Vagankovo

Currently when you send a private message, you get a nondescript `Message sent.`, which makes it harder to talk. The changes will make /msg give out `To <RECEPIENT>: <MESSAGE>`.

2022-08-25 17:10 UTC, magnetar47 requested changes
Not sure if this change is worth it, but since you've made a PR yourself, then why not.

2022-08-25 17:10 UTC, magnetar47 commented on mods/ctf/ctf_chat/init.lua
> +		str = "To " .. name .. ": " .. message
`name` is the player name of the sender, not the receiver. See L#24 above. The PM goes to the recipient like so: `PM from <name>: ...`. So if you use `name` here, then the sender will see their own name. Recipient's name is stored in the `sendto` var (see [here](https://github.com/MT-CTF/capturetheflag/blob/88fc9e15549af1ba95d764079f1617a553baa8a6/mods/ctf/ctf_chat/init.lua#L9)).

I'd also like to see the recipient name `minetest.colorize`-d for consistency.

2022-08-25 17:14 UTC, Vagankovo commented on mods/ctf/ctf_chat/init.lua
> +		str = "To " .. name .. ": " .. message
Thanks for the catch, I only tested in singleplayer.

As of the colorization, Vagnar said in Discord that it should stay white *as is*: https://discord.com/channels/447819017391046687/1012316794062639184/1012350458884534382

2022-08-26 18:53 UTC, Vagankovo commented on mods/ctf/ctf_chat/init.lua
> +		str = "To " .. name .. ": " .. message
Isn't this supposed to be resolved after our conversation, or did I miss something?

2022-08-28 14:28 UTC, LoneWolfHT approved these changes

2022-08-28 14:29 UTC, merged

2022-08-29 05:26 UTC, magnetar47 commented on mods/ctf/ctf_chat/init.lua
> +		str = "To " .. name .. ": " .. message
Sorry, I went AFK halfway through this conversation. :P