Poisonous grenade
MT-CTF/capturetheflag pull request #1091
Opened 2023-02-03 08:39 UTC by farooqkz

This PR adds poisonous grenade to the game which poison enemy team members when inside or very close to the smoke.

The poison will never damage the thrower or thrower team. It won't damage the thrower even if they change team.

![screenshot_20230203_115918](https://user-images.githubusercontent.com/15038218/216551964-114cf205-90af-4399-a611-7c147adb9ce7.png)

2023-02-03 16:04 UTC, LoneWolfHT requested changes
![image](https://user-images.githubusercontent.com/28972859/216649826-893c48b2-275d-482d-bb0f-f41f15fd7ad6.png)
Your PRs keep getting worse and worse baggage-wise.

You didn't base this PR off of the parent repo's master, so your team spike changes are included in this PR.
You also still have the map submodule issue, it would be nice if we could figure out how to fix that

2023-02-03 16:23 UTC, farooqkz commented
> ![image](https://user-images.githubusercontent.com/28972859/216649826-893c48b2-275d-482d-bb0f-f41f15fd7ad6.png) Your PRs keep getting worse and worse baggage-wise.

lol. My apologies! Perhaps I'm too much in a hurry or perhaps I'm overloading myself.

> You didn't base this PR off of the parent repo's master, so your team spike changes are included in this PR. You also still have the map submodule issue, it would be nice if we could figure out how to fix that

Well I did `git checkout -b poison up/master` where `up` is the upstream. Perhaps I've been doing so wrong all the time?

2023-02-03 16:40 UTC, farooqkz commented
Ready for another review

2023-02-03 16:55 UTC, LoneWolfHT requested changes
There should be no nodes/abms involved in this.
Get the poison grenade explosion pos and check it against the position of all online players in a minetest.after(1) loop that stops when the smoke does

2023-02-03 17:28 UTC, farooqkz commented
> Nice, it worked.
> 
> There should be no nodes/abms involved in this. Get the poison grenade explosion pos and check it against the position of all online players in a minetest.after(1) loop that stops when the smoke does

May I ask why?

2023-02-03 18:12 UTC, LoneWolfHT commented
> May I ask why?

ABMs are terribly inefficient, and temporary nodes like your poison one should be avoided whenever possible, since they rely on the explosion area meeting certain conditions (like not being underwater or containing nodes with non-default collisionboxes), and there are usually faster solutions

2023-02-04 16:51 UTC, farooqkz commented
> > May I ask why?
> 
> ABMs are terribly inefficient, and temporary nodes like your poison one should be avoided whenever possible, since they rely on the explosion area meeting certain conditions (like not being underwater or containing nodes with non-default collisionboxes), and there are usually faster solutions

I'm stuck here. See my latest commit.

2023-02-06 15:39 UTC, LoneWolfHT requested changes

2023-02-06 15:39 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +					minetest.after(1, self)
You can pass `damage_fn` instead of `self` IIRC

2023-02-06 15:39 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +						local name = object:get_player_name()
Missing `object:is_player()` check. I think it would be faster to loop through all online players and compare their positions though.
AFAIK `minetest.get_objects_inside_radius()` does that anyway, it just does it with all objects on the server

2023-02-06 15:40 UTC, LoneWolfHT commented
You got quite far, nice work

2023-02-06 15:41 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +					minetest.after(1, self)
(remember to remove `self` from the arg list, I don't think anything will call for it)

2023-02-07 02:01 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +					minetest.after(1, self)
done

2023-02-07 02:03 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +						local name = object:get_player_name()
`object:is_player()` is not needed. `object:get_player_name()` is used which returns empty string for non players and it is compared against thrower name.

2023-02-07 09:49 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +						local name = object:get_player_name()
I think it's better to check

2023-02-07 09:51 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +						local name = object:get_player_name()
Done

2023-02-08 20:39 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +					local objects = minetest.get_objects_inside_radius(pos, 6)
```suggestion
		    if damage then
		    	local stop = false
		    	minetest.after(bla, function() stop = true end)
				local function damage_fn()
					if stop then return end
					local objects = minetest.get_objects_inside_radius(pos, 6)
```

You can do something like this to stop the smoke after a certain amount of time. I'd recommend putting the `minetest.after()` next to the initial `damage_fn()` call though

2023-02-08 20:39 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +					local objects = minetest.get_objects_inside_radius(pos, 6)
(I don't recommend committing this suggestion)

2023-02-09 09:15 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +					local objects = minetest.get_objects_inside_radius(pos, 6)
Done

2023-02-09 21:11 UTC, LoneWolfHT requested changes

2023-02-09 21:11 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +				minetest.after(SMOKE_GRENADE_TIME, function() stop = true end)
This should go in the `minetest.after(SMOKE_GRENADE_TIME` on line 191

2023-02-09 21:11 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +						if dname ~= pname and object:is_player() and dteam ~= pteam then
> I think it would be faster to loop through all online players and compare their positions though.

Thisstill needs to be done ^

2023-02-12 13:20 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +				minetest.after(SMOKE_GRENADE_TIME, function() stop = true end)
done

2023-02-12 13:20 UTC, farooqkz commented on mods/pvp/grenades/grenades.lua
> +						if dname ~= pname and object:is_player() and dteam ~= pteam then
done

2023-02-13 01:35 UTC, LoneWolfHT requested changes
Probably ready for testing after this

2023-02-13 01:35 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +				end
```suggestion
				local function damage_fn()
					local thrower = minetest.get_player_by_name(pname)
					for _, target in pairs(minetest.get_connected_players()) do
						if vector.distance(target:get_pos(), pos) <= 6 then
							local dname = target:get_player_name()
							local dteam = ctf_teams.get(dname)
							if dname ~= pname and dteam ~= pteam then
								target:punch(thrower, 10, {
									damage_groups = {
										fleshy = 1,
										poison = 1,
									}
								})
							end
						end
					end
					if not stop then
						minetest.after(1, damage_fn)
					end
				end
```

2023-02-13 01:35 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +				minetest.remove_node(pos)
Leftover code
```suggestion
```

2023-02-13 01:35 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +				particletexture = p .. "colorize:" .. ctf_teams["team"][ctf_teams.get(pname)].color .. ":50"
```suggestion
			if pteam and damage then
				particletexture = p .. "colorize:" .. ctf_teams.team[pteam].color .. ":50"
```

2023-02-13 13:54 UTC, farooqkz commented
I don't check Discord anymore. Please let me know regarding the test session(when and where).

2023-02-16 03:30 UTC, LoneWolfHT commented
It'll probably take a while. I need to finish working on something else that I want to test

2023-02-16 11:00 UTC, farooqkz commented
You want to test this and that together?

2023-02-21 21:42 UTC, LoneWolfHT commented
@farooqkz What timezone are you in, and what would an ideal testing time be?

2023-02-22 16:01 UTC, farooqkz commented
> @farooqkz What timezone are you in, and what would an ideal testing time be?

The ideal time window for me would be 12-18(UTC)

2023-02-25 20:47 UTC, farooqkz commented
@LoneWolfHT When is the testing session? or perhaps yet undecided?

2023-02-25 20:55 UTC, LoneWolfHT commented
14:30 UTC on February 27
Are you able to talk on Discord when the time arrives?

2023-02-25 21:00 UTC, farooqkz commented
> 14:30 UTC on February 27 Are you able to talk on Discord when the time arrives?

The time seems okay for me. But I won't be able to log into Discord anytime soon.

2023-02-26 06:22 UTC, LoneWolfHT commented
> > 14:30 UTC on February 27 Are you able to talk on Discord when the time arrives?
> 
> The time seems okay for me. But I won't be able to log into Discord anytime soon.

How about IRC/Matrix?
If not those then you'll have to join the main server for the address/port I guess

2023-02-26 10:16 UTC, farooqkz commented
> > > 14:30 UTC on February 27 Are you able to talk on Discord when the time arrives?
> > 
> > 
> > The time seems okay for me. But I won't be able to log into Discord anytime soon.
> 
> How about IRC/Matrix? If not those then you'll have to join the main server for the address/port I guess

I am available on them.

2023-02-27 17:37 UTC, LoneWolfHT commented
1. the poison must not get thrown to enemy base. it will do spawnkill
2. the poison has punch image for kill log

2023-02-27 19:34 UTC, farooqkz commented
Regarding kill log, I need some hints. And what do you mean the colour must be stronger?

2023-02-27 20:35 UTC, LoneWolfHT commented
> And what do you mean the colour must be stronger?

It should be less grey/have more color to it

You can change the kill log image in this function: https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_modebase/features.lua#L23-L46

2023-02-27 20:38 UTC, LoneWolfHT commented
Added the TODO list to the main post

2023-02-28 13:57 UTC, farooqkz commented
@LoneWolfHT ready for review

2023-03-01 04:33 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +						if distance_from_flag <= 25 then
```suggestion
						elseif distance_from_flag <= 25 then
```

2023-03-01 04:33 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +				particletexture = p .. "colorize:" .. ctf_teams.team[pteam].color .. ":76"
```suggestion
				particletexture = p .. "colorize:" .. ctf_teams.team[pteam].color .. ":76^[noalpha"
```

2023-03-02 17:13 UTC, merged

2023-03-02 18:13 UTC, LoneWolfHT commented
>  the poison has punch image for kill log
This wasn't fixed. I've done so in https://github.com/MT-CTF/capturetheflag/commit/f4a8d72b6211ead1e9fe3afdea09f91e2e67ba2c