A few additions to the README.md
MT-CTF/capturetheflag pull request #1144
Opened 2023-05-01 13:56 UTC by src4026

Some extra information and clarifying edits.

2023-05-05 11:34 UTC, farooqkz approved these changes
LGTM

2023-05-05 11:36 UTC, farooqkz commented on mods/ctf/ctf_map/README.md
> +	- "Indestructible Red Barrier Stone" (`ctf_map:ind_stone_red`) for underground build-time wall. This will turn to Normal Stone (`default:stone`) once the match begins.
```suggestion
	- "Indestructible Red Barrier Stone" (`ctf_map:ind_stone_red`) for underground build-time wall. This will turn to stone (`default:stone`) once the match begins.
```

2023-05-05 11:40 UTC, farooqkz requested changes

2023-05-05 11:40 UTC, farooqkz commented on mods/ctf/ctf_map/README.md
> +Whether or not the map is available for play. You will want to tick this.
```suggestion
Whether or not the map is available for play. You will want to check this.
```

2023-05-05 11:40 UTC, farooqkz commented on mods/ctf/ctf_map/README.md
> +* We can only accept Free Software licenses, e.g. `CC BY-SA 4.0`.
```suggestion
* We can only accept the free culture licences like `CC BY-SA 4.0`. Note that not licences in the Creative Commons family are free(as in freedom). For instance those with `ND` are not.
```

2023-05-05 11:40 UTC, farooqkz commented on mods/ctf/ctf_map/README.md
> +### 7. Play
```suggestion
### 7. Play
```

2023-05-05 11:43 UTC, farooqkz commented
My review is not complete, yet. I'm busy elsewhere.

2023-05-05 11:51 UTC, src4026 commented
I clicked resolve. Was it the correct option? Thanks for the formatting and other stuff.

2023-05-05 11:55 UTC, farooqkz commented
No you clicked the wrong button :)

You should commit my suggestions if you agree with them.

2023-05-05 11:56 UTC, src4026 commented
> No you clicked the wrong button :)
> 
> You should commit my suggestions if you agree with them.

Oh lel. I am on phone so I might need to navigate a bit more.

2023-05-05 12:02 UTC, src4026 commented
I switched to my browser and committed some changes. Did it work? ^π^

2023-05-05 12:18 UTC, farooqkz commented
> I switched to my browser and committed some changes. Did it work? ^π^

Yes but more review is required. Also I appreciate your work and effort. Hopefully, you'll learn Lua and contribute code as well :)

2023-05-05 12:21 UTC, src4026 commented
> Yes but more review is required. Also I appreciate your work and effort. Hopefully, you'll learn Lua and contribute code as well :)

Yes, more work has to be done. Thanks :D.

2023-05-05 12:38 UTC, src4026 commented
Btw I did learn Lua. I just have to start with Minetest modding basics whenever I get sufficient time.

2023-05-06 05:08 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +> "What about flags?," you may ask. Well, check the next section to see how to add them to your map.
@a-blob , I thought it would be appropriate to add since "Team chests" are mentioned. Let's see what the other have to say about it.

2023-05-06 05:13 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +> **Important:** If you ever want to exit the world in which you are making the map and want to come back to it later, simply exit it (**do not** press "Finish Editing in the CTF map editor). When yo
Looks like there's a loophole. This means that `/ctf_map editor should only be run at the end. I'll have to check in with some of the map managers to verify this.

2023-05-06 05:13 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +	- "Indestructible Red Barrier Glass" (`ctf_map:ind_glass_red`) for the build-time wall. The setting to make it disappear upon the beginning of the match will be set at last when you will run `/ctf_m
@a-blob IIRC there is a barrier area. That's what Hobbit Power told me.

2023-05-06 05:16 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +1. `Map Shadow Intensity`: Sets the intensity of the shadows.
In the `ctf_map editor` it was "Map Shadow Intensity".

2023-05-06 05:18 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +Area where the Indestructible "Red Barrier Glass and/or Indestructible Red Barrier Stone" wall is located. Setting this will allow the game to know where to make them disappear when the match begins.
Oh is it?

2023-05-06 06:08 UTC, a-blob commented on mods/ctf/ctf_map/README.md
> +Area where the Indestructible "Red Barrier Glass and/or Indestructible Red Barrier Stone" wall is located. Setting this will allow the game to know where to make them disappear when the match begins.
I tested, it's automatically set to be the same as the map corners.

2023-05-06 06:21 UTC, a-blob commented on mods/ctf/ctf_map/README.md
> +Area where the Indestructible "Red Barrier Glass and/or Indestructible Red Barrier Stone" wall is located. Setting this will allow the game to know where to make them disappear when the match begins.
```suggestion
Area where the Indestructible "Red Barrier Glass and/or Indestructible Red Barrier Stone" wall is located. Setting this will allow the game to know where to make them disappear when the match begins. You can leave this by default unless the game is taking a long time to remove your barriers.
```

2023-05-06 06:22 UTC, a-blob commented on mods/ctf/ctf_map/README.md
> +	- "Indestructible Red Barrier Glass" (`ctf_map:ind_glass_red`) for the build-time wall. The setting to make it disappear upon the beginning of the match will be set at last when you will run `/ctf_m
If you mean that, then yes, but it's confusing and not necessary to mention it here.

2023-05-07 12:25 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +> "What about flags?," you may ask. Well, check the next section to see how to add them to your map.
@a-blob should I mark this as resolved or are changes needed?

2023-05-10 02:02 UTC, a-blob commented on mods/ctf/ctf_map/README.md
> +> "What about flags?," you may ask. Well, check the next section to see how to add them to your map.
You decide, since you are the author of this pull request.

2023-05-13 10:38 UTC, HobbitPower commented on mods/ctf/ctf_map/README.md
> +> "What about flags?," you may ask. Well, check the next section to see how to add them to your map.
I agree with @a-blob There is no need for this sentence imo.

2023-05-13 10:42 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +> **Important:** If you ever want to exit the world in which you are making the map and want to come back to it later, simply exit it (**do not** press "Finish Editing in the CTF map editor). When yo
I had mistakenly resolved it

2023-05-13 10:49 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +> **Important:** If you ever want to exit the world in which you are making the map and want to come back to it later, simply exit it (**do not** press "Finish Editing in the CTF map editor). When yo
Hmm. Looks like I have to fix the wrong commit when I reach home.

2023-05-14 14:12 UTC, farooqkz reviewed
Not sure if it's a good idea to use HTML tags in markdown. Some consider it a bad idea and I am almost neutral on this but prefer to not do it anyway.

2023-05-14 14:15 UTC, src4026 commented
> Not sure if it's a good idea to use HTML tags in markdown. Some consider it a bad idea and I am almost neutral on this but prefer to not do it anyway.

Could you mention another way to show the `*required` that wouldn't be using the HTML tag? :D I suppose it would be safer not using HTML. :shrug:

2023-05-14 14:47 UTC, farooqkz commented on mods/ctf/ctf_map/README.md
> +#### Map Enabled <sup><em>(*required)</em></sup>
```suggestion
#### Map Enabled *(required)*
```

2023-05-14 15:52 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +#### Map Enabled <sup><em>(*required)</em></sup>
Ig HTML has to go…

2023-06-10 09:38 UTC, src4026 commented
@a-blob I have added this line instead of the method that wasted the placement of the corners etc.:
```md
### 6. Export 

1. Press "Finish Editing"
2. Find the exported map located in `[Mintest folder]/worlds/[Map World]/schems/[Exported Map folder]`
3. Move the exported map folder to `\[Minetest folder]/games/capturetheflag/mods/ctf/ctf_map/maps`.

You can access the exported map by running `/ctf_map editor`, clicking on the exported map folder from the list of maps, and then by pressing "Start Editing". 
```
I suppose it is obvious that the maker has to repeat the process for every edit they make onwards?

2023-06-25 18:16 UTC, LoneWolfHT commented on mods/ctf/ctf_map/README.md
> +5. *Optional:* Enable `worldedit`
```suggestion
4. *Optional:* Enable `worldedit`
```

2023-06-28 19:34 UTC, src4026 commented on mods/ctf/ctf_map/README.md
> +If you choose to submit your map, include a screenshot of it in the exported map's folder. It should be taken with on texture packs enabled and have an aspect ratio of 3:2 (screenshot 600x400px is su
My bad, I was supposed to write "no" :sweat_smile:. Your edit is better. TBH, I was confused whether I did word or as no texture packs enabled or default xD.

2023-08-03 13:11 UTC, src4026 commented
I have made some changes, so I request a review. Also, is there anything stopping the merge of this PR or is it that it is still incomplete?

2023-08-21 18:09 UTC, merged