Add marker blacklists
MT-CTF/capturetheflag pull request #1149
Opened 2023-05-18 05:10 UTC by FlamingRCCars

When zooming and using rifles, you will not leave markers.

2023-05-18 07:41 UTC, farooqkz commented
From what I understood, this PR prevents marker placement while wielding a variety of guns which I think is not something people want.

2023-05-18 15:30 UTC, FlamingRCCars commented
13-0 voted yes on this feature: https://discord.com/channels/447819017391046687/448136308108296213/1082317387845615676

2023-05-18 15:30 UTC, FlamingRCCars commented
> From what I understood, this PR prevents marker placement while wielding a variety of guns which I think is not something people want.

13-0 voted yes on this feature: https://discord.com/channels/447819017391046687/448136308108296213/1082317387845615676

2023-06-30 17:11 UTC, LoneWolfHT requested changes

2023-06-30 17:11 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +					return
This will cancel zoom checks for all other players. Add a variable to track if they're holding a gun and put the following code in an if statement checking that variable

2023-06-30 23:44 UTC, FlamingRCCars commented on mods/ctf/ctf_modebase/markers.lua
> +					return
I didn't fully understand what you meant, but I believe the changes I pushed are correct.

2023-07-01 22:51 UTC, merged