Add HP Markers
MT-CTF/capturetheflag pull request #1159
Opened 2023-06-10 08:21 UTC by src4026

In reference to #1158.
## What I have done:
- Added a new `capturetheflag/mods/ctf/ctf_modebase/hpmarkers.lua` file and included it in `capturetheflag/mods/ctf/ctf_modebase/init.lua`.
- Added the commands `/hp`, `/hpp` (I may remove it since it is not useful), `hpr`.

## Issues to be resolved and improvements to be made:
- Removing unnecessary code from the `hpmarkers.lua` file.
- Enable only for classes (there is a bandage in nade too, isn't it? Is it necessary to add the HP marker to both the modes or just classes?)
- Change the message to also include the total hp of the class 
- (Should the HP marker colour be the same as the colour for normal markers?)
- other stuff that I may have missed while writing this description :P.

2023-06-10 08:33 UTC, src4026 commented
## Adding to "Issues to be resolved and improvements to be made:":
- Errors
- Improved HP marker message

2023-06-10 14:09 UTC, farooqkz commented
IMO, you are greatly overdoing it. There shouldn't be an extra hpmarker thing and commands to remove it. HP Markers are normal markers except that you mark your own position and your current hp plus your max hp is in the label. So no need for tracking HP markers separately and another command to remove them.

Also hp marker for another player was not requested and I think it is not needed. I am against adding that. We can however, include hp and max hp of the normal marker target if it's a player.

2023-06-10 15:23 UTC, src4026 commented
> IMO, you are greatly overdoing it. There shouldn't be an extra hpmarker thing and commands to remove it. HP Markers are normal markers except that you mark your own position and your current hp plus your max hp is in the label. So no need for tracking HP markers separately and another command to remove them.
> 
> Also hp marker for another player was not requested and I think it is not needed. I am against adding that. We can however, include hp and max hp of the normal marker target if it's a player.

Yes, you are right. The process of cleaning up the code that I'll be doing in the near future wasn't only for that file itself, but for the HP marker mechanism as a whole. I have made these files only for temporary reference.

2023-06-10 17:19 UTC, src4026 commented
@farooqkz, If I am correctly understanding your previous comment, you mean you want to make merge them into a single file with the HP markers as a part of the normal markers? I tried doing it, but I ran into some issues, which, I believe, are mostly by my incompetence of not knowing much about the code I am working on.

2023-06-10 17:57 UTC, src4026 commented
> @farooqkz, If I am correctly understanding your previous comment, you mean you want to merge them into a single file with the HP markers as a part of the normal markers? I tried doing it, but I ran into some issues, which, I believe, are mostly by my incompetence of not knowing much about the code I am working on.

2023-06-10 21:01 UTC, farooqkz commented
There is already code which places markers. 

1. Find that code.
2. If it's not already the case, create a function to create markers
3. Re-implement `/m` and other commands with your new function
4. Add `/hp` which uses the marker placement function.

2023-06-11 05:55 UTC, src4026 commented
> There is already code which places markers. 
> 
> 1. Find that code.
> 2. If it's not already the case, create a function to create markers
> 3. Re-implement `/m` and other commands with your new function
> 4. Add `/hp` which uses the marker placement function.

That is what I tried doing yesterday. I ran into some errors. I'll retry again, and if I get stuck, I'll post the code along with the error :+1:.

2023-06-11 13:56 UTC, farooqkz commented
Looks much better now but it's not my final review :)

2023-06-11 14:11 UTC, farooqkz commented
Okay. I recommend reusing the existing code by calling `marker_func` in `hpmarker_func`. However `marker_func` by default adds a marker according to player eye direction. I suggest adding another parameter(last parameter) to `marker_func` which is the looking direction. By default when it is called by `/m` it's nil and therefore it checks the player's looking direction. But when supplied, it uses that instead of actual looking direction of the player calling it. And you use that through `/hp`

2023-06-11 14:24 UTC, src4026 commented
> Okay. I recommend reusing the existing code by calling `marker_func` in `hpmarker_func`. However `marker_func` by default adds a marker according to player eye direction. I suggest adding another parameter(last parameter) to `marker_func` which is the looking direction. By default when it is called by `/m` it's nil and therefore it checks the player's looking direction. But when supplied, it uses that instead of actual looking direction of the player calling it. And you use that through `/hp`

Hmm. I will look into it later when I can. Thanks 👍

2023-06-12 18:11 UTC, src4026 commented
I reused the `marker_func` in `hpmarker_func`. I understand clearly why you want me to reuse it - DRY =P - because of my previous programming knowledge, but since I am very new to Lua, I need to get used to its syntax and proper usage. So, after I did that reusing, here's what I got. It may not be the best :)

2023-06-12 18:19 UTC, src4026 commented
Note: There is an issue that if an HP marker is placed, it apparently doesn't set a marker cooldown (?). I tried seeing the code, but can't seem to find anything at first glance. I will be having a look at it for 10 minutes from now, and if I can't find it, that will be indicated my no pushes to this PR since the last one.

2023-06-12 18:25 UTC, src4026 commented
I can't seem to find the exact reason why this is happening. Bye. I have got to sleep, see you all tomorrow :zzz:

2023-06-12 18:25 UTC, farooqkz commented
> Note: There is an issue that if an HP marker is placed, it apparently doesn't set a marker cooldown (?). I tried seeing the code, but can't seem to find anything at first glance. I will be having a look at it for 10 minutes from now, and if I can't find it, that will be indicated my no pushes to this PR since the last one.

Feel free to take your time and come back later. I will look into it tomorrow, God willing. And try to help if you hadn't figured it out till then.

2023-06-13 09:32 UTC, src4026 commented
> > Note: There is an issue that if an HP marker is placed, it apparently doesn't set a marker cooldown (?). I tried seeing the code, but can't seem to find anything at first glance. I will be having a look at it for 10 minutes from now, and if I can't find it, that will be indicated my no pushes to this PR since the last one.
> 
> Feel free to take your time and come back later. I will look into it tomorrow, God willing. And try to help if you hadn't figured it out till then.

I tested it, and found that the timer works, but it doesn't print the message saying that "You can place markers every 5 seconds". The code seems fine. Is the way I have called the function the cause of the issue, or that I have mixed a loop block on accident with another one?

2023-06-13 11:04 UTC, farooqkz commented
Other than the code suggestion I made, I also suggest this:

``lua
if hpmarker then
    -- code A
else
   -- code B
end
```

rather than this:

```lua
if hpmarker == nil then
  -- code B
else
  -- code A
end
```

2023-06-13 11:57 UTC, src4026 commented
> I tested it and LGTM
So the text not appearing is fine?

2023-06-15 18:35 UTC, farooqkz commented
> 

What text?

2023-06-16 02:21 UTC, src4026 commented
> > 
> 
> What text?

The one that appears if you try to place markers before the time limit. The timer works and the markers aren't placed, but the message doesn't show for HP markers when I tested it.

2023-06-16 02:21 UTC, src4026 commented
> I am looking forward to see the first code contribute of you merged :)

Me too :D

2023-06-16 11:50 UTC, farooqkz commented
> > > 
> > 
> > 
> > What text?
> 
> The one that appears if you try to place markers before the time limit. The timer works and the markers aren't placed, but the message doesn't show for HP markers when I tested it.

Ah I see.

2023-06-16 11:54 UTC, farooqkz commented on mods/ctf/ctf_modebase/markers.lua
> +	func = function(name, param, specific_player) marker_func(name, param, specific_player, true) end
```suggestion
	func = function(name, param, specific_player) return marker_func(name, param, specific_player, true) end
```

2023-06-16 11:55 UTC, farooqkz commented
@src4026 try my suggestion please

2023-06-16 12:41 UTC, src4026 commented
> @src4026 try my suggestion please

Oh sorry, I didn't see.

2023-06-16 12:44 UTC, src4026 commented
Ah. So it was indeed the way the function was called. I learned something :D

2023-06-29 18:28 UTC, LoneWolfHT commented
Are the issues listed in OP resolved then?

2023-06-29 18:43 UTC, farooqkz commented
yes as i recall. except that it is enabled for all modes.

2023-06-29 19:16 UTC, LoneWolfHT reviewed
One other option would be to add the player's HP to their marker if the marker is within ~2 blocks from them. So to request heals they can just mark at their feet

2023-06-29 19:16 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
>  	))
```suggestion

		local ray = minetest.raycast(
			pos1, vector.add(pos1, vector.multiply(player:get_look_dir(), MARKER_RANGE),
			true, false
		))
```

2023-06-29 21:04 UTC, farooqkz commented
> One other option would be to add the player's HP to their marker if the marker is within ~2 blocks from them. So to request heals they can just mark at their feet

I am unsure if I agree as it adds an extra step for placing a HP marker which is bad in the case of emergency.

2023-06-29 21:08 UTC, farooqkz commented
Another idea: Distinguish HP markers and normal markers in the chat.

2023-06-30 02:04 UTC, src4026 commented
> Another idea: Distinguish HP markers and normal markers in the chat.

I was initially thinking about that too. Perhaps a cyan colour since it isn't used in CTF?

2023-06-30 12:39 UTC, farooqkz commented
> > Another idea: Distinguish HP markers and normal markers in the chat.
> 
> I was initially thinking about that too. Perhaps a cyan colour since it isn't used in CTF?

I would make it coloured like other markers but with a different message.

@LoneWolfHT What do you think?

2023-06-30 16:37 UTC, src4026 commented
Proposal for message:
> \<player\> needs medical help! HP=<player's hp>

2023-06-30 16:38 UTC, src4026 commented
> Proposal for message:
> \<player\> placed an HP marker. 
> \<player\> needs medical help! HP=<player's hp>

2023-06-30 16:39 UTC, farooqkz commented
"medical attention" sounds more natural to me than "medical help"

2023-06-30 16:39 UTC, src4026 commented
Something like the above? Also, will HP markers be available for all the modes or be restricted to classes only?

2023-06-30 16:40 UTC, src4026 commented
> "medical attention" sounds more natural to me than "medical help"

Yup 👍

2023-06-30 16:53 UTC, LoneWolfHT commented
> I am unsure if I agree as it adds an extra step for placing a HP marker which is bad in the case of emergency.

It would be one less step, because you'd be using the normal markers you're used to placing, you just place it at your feet.
The quick markers (Zoom+Mousebutton) would work for it too

2023-06-30 16:54 UTC, LoneWolfHT commented
> Something like the above? Also, will HP markers be available for all the modes or be restricted to classes only?

HP markers should only be allowed in the modes that have normal markers

2023-06-30 16:55 UTC, LoneWolfHT commented
> Another idea: Distinguish HP markers and normal markers in the chat.

Could probably do this by putting the marker's text in the chat message

2023-07-01 09:34 UTC, farooqkz commented
@src4026 @LoneWolfHT I think the idea of pointing to your feet for HP marker is a good idea. However, I think there must be the command there as well.

@LoneWolfHT If you agree, @src4026 can keep the current command and add what you suggested as well.

2023-07-01 13:17 UTC, src4026 commented
The addition of the player points at their feet and places a marker I also feel is good as LV suggested. So I'll be adding that as an extension, isn't it?

2023-07-01 14:31 UTC, farooqkz commented
> The addition of the player points at their feet and places a marker I also feel is good as LV suggested. So I'll be adding that as an extension, isn't it?

You can simply check for pointed thing against players position and if it's close enough(as LV/LW suggested, less than 2 blocks), simply set the `hpmarker` to `true`.

2023-07-01 22:28 UTC, LoneWolfHT commented
Having the command still works. it might be a good idea to rename it to `/mhp` though

2023-07-02 11:19 UTC, src4026 commented
Ready for review :D

2023-07-02 11:28 UTC, src4026 commented
Also, I'll update the description in a minute or two. 👍

2023-07-02 11:31 UTC, farooqkz commented on mods/ctf/ctf_modebase/markers.lua
> +	if (math.abs(pos.x - player:get_pos().x) <= 2) and (math.abs(pos.y - player:get_pos().y) <= 2) and (math.abs(pos.z - player:get_pos().z) <= 2) then
```suggestion
	if vector.distance(pos, player:get_pos()) <= 2 then
```

2023-07-02 11:57 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +	if (math.abs(pos.x - player:get_pos().x) <= 2) and (math.abs(pos.y - player:get_pos().y) <= 2) and (math.abs(pos.z - player:get_pos().z) <= 2) then
Ah yes, of course MT has a way to directly find the vector distances.

2023-07-02 14:08 UTC, src4026 commented
> ## Issues to be resolved and improvements to be made:
> - Colouring and chat message changes to be discussed upon.

So, is this what is left of now?

2023-07-03 19:59 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +	func = function(name, param, specific_player) return marker_func(name, param, specific_player, true) end
The `func` function of chatcommands only passes two arguments, did you test this code?

2023-07-03 19:59 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +	if vector.distance(pos, player:get_pos()) then
This code currently checks if distance exists between the player and the marker pos. I think you forgot to add a `<= 2` here :P

2023-07-03 20:01 UTC, LoneWolfHT commented
> * Colouring and chat message changes to be discussed upon.

I answered this earlier:
> Could probably do this by putting the marker's text in the chat message

Coloring the marker messages differently can be done in a different PR

2023-07-04 01:55 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +	func = function(name, param, specific_player) return marker_func(name, param, specific_player, true) end
IIRC that's how Farooq had made the marker changes to be to make the function reusable. There's a part of me still I'm confusion about this 😅

2023-07-04 01:56 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +	if vector.distance(pos, player:get_pos()) then
Ah yes, my bad :D

2023-07-04 01:57 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +	if vector.distance(pos, player:get_pos()) then
But it worked when I was testing it lol. Perhaps somewhere in copy/pasting the code and changing for messed up.

2023-07-04 02:04 UTC, src4026 commented
> > * Colouring and chat message changes to be discussed upon.
> 
> I answered this earlier:
> > Could probably do this by putting the marker's text in the chat message
> 
> Coloring the marker messages differently can be done in a different PR

So I suppose now all is well except that function you're talking about in the above review. :+1:

2023-07-04 06:34 UTC, farooqkz commented on mods/ctf/ctf_modebase/markers.lua
> +	func = function(name, param, specific_player) return marker_func(name, param, specific_player, true) end
```suggestion
	func = function(name, param) return marker_func(name, param, nil, true) end
```

@src4026 did it wrong but because in Lua an argument not provided is `nil`, it didn't cause any problem and it works. This suggestion makes it better.

2023-07-04 06:41 UTC, farooqkz requested changes
You need to make small changes as there are bugs.
Now, if the player tries to place HP marker using `mhp`, if they are not pointing to anything, no HP marker is placed and the player is told they are pointing nothing. You should move the code to check player distance and checking `hpmarker` for being `true` to the beginning of the function and immediately place the hp marker and return. This way first, if the player wanted to just place a HP marker, no calculation of ray stuff and such these is done in vain and second, the bug is easily solved.

2023-07-04 11:04 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +	func = function(name, param, specific_player) return marker_func(name, param, specific_player, true) end
Sorry for that, commiting suggestion.

2023-07-04 11:50 UTC, src4026 commented
~~There's literally a comment in the next line and I've tried to clear every whitespace~~

2023-07-04 11:51 UTC, farooqkz commented
@src4026 Ping me when you are finished.

2023-07-04 11:52 UTC, src4026 commented
@farooqkz luacheck is giving an error although as far as I can see there is no trailing whitespace.

2023-07-04 12:03 UTC, src4026 commented
Why did luacheck show an error where it was not located?

2023-07-04 12:03 UTC, src4026 commented
Also, ty Farooq for fixing them :)

2023-07-04 12:08 UTC, farooqkz commented
For me luacheck did not false alarm. The problem could possibly be with your editor and/or its configuration. The main reason I did the changes was that you didn't seem to have fixed the bugs properly and I was too lazy too explain you what to do. So I did it myself in the hope that you realize where you were wrong by comparing my code and your code.

2023-07-04 12:09 UTC, farooqkz commented
@LoneWolfHT It's ready for review. But there's one last thing: What if the player is pointing to somewhere near(maximum two blocks away as you said) but pointing to an object? I think the HP marker must be placed only if the player is pointing to the node under.

2023-07-04 13:11 UTC, src4026 commented
> For me luacheck did not false alarm. The problem could possibly be with your editor and/or its configuration. The main reason I did the changes was that you didn't seem to have fixed the bugs properly and I was too lazy too explain you what to do. So I did it myself in the hope that you realize where you were wrong by comparing my code and your code.

Yes, I do understand it now. And my editor has become a bit messy with the switching and everything.

2023-07-04 16:46 UTC, LoneWolfHT commented
> @LoneWolfHT It's ready for review. But there's one last thing: What if the player is pointing to somewhere near(maximum two blocks away as you said) but pointing to an object? I think the HP marker must be placed only if the player is pointing to the node under.

That's one solution, you could also just append the player's HP to that object marker too (`My HP: x/x` or something)

2023-07-04 16:52 UTC, src4026 commented
> > @LoneWolfHT It's ready for review. But there's one last thing: What if the player is pointing to somewhere near(maximum two blocks away as you said) but pointing to an object? I think the HP marker must be placed only if the player is pointing to the node under.
> 
> That's one solution, you could also just append the player's HP to that object marker too (`My HP: x/x` or something)

So which one should I implement here? I'll do it after you guys agree on one 👍

2023-07-04 17:19 UTC, LoneWolfHT commented
The one I suggested will work even if there's an object at your feet, so that might be a better one

2023-07-04 18:06 UTC, src4026 commented
I will do it tomorrow. Thanks for the suggestions and feedback :D

2023-07-07 17:45 UTC, src4026 commented
I had been working on it but had some local conflicts with a lot of folder. I need more time, sorry for making wrong commitments regarding the time within which I will be able to complete it. Thanks

2023-07-07 18:55 UTC, farooqkz commented
No worries there is absolutely no rush :)

2023-07-08 11:08 UTC, src4026 commented
There might be some redundancy, but I tried not resolving it for the time being. Also, I will be making one more commit, one sec :+1:

2023-07-08 11:15 UTC, src4026 commented
#### Possible feature suggestion:
- If a player is pointing at another player with low HP, then the other player's HP will be appended to the marker.

2023-07-08 18:17 UTC, LoneWolfHT requested changes

2023-07-08 18:17 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
Weird indentation here. `pointed` can also be nil here too I think

2023-07-08 18:17 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +          concat = string.match(itemdef.description or entity.itemstrng, "([^\n]+)")
Misspelling of itemstring here. Did you modify any other parts of this? It's all shown as a change in Github so it's hard for me to tell

2023-07-08 18:39 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
I did that to perhaps prevent the error that luacheck shows when a line is long.

2023-07-08 18:44 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
Tested it and it is indeed `nil`. I will have to fix that :+1:

2023-07-08 18:50 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
It should work now. Is the way I have done the proper way or is another better way possible?

2023-07-08 18:59 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
> I did that to perhaps prevent the error that luacheck shows when a line is long. Also, I did test the markers in-game and if I haven't missed a case, then they should work fine.

NEVER sacrifice indentation for luacheck warnings. Try putting a newline in these places 
![image](https://github.com/MT-CTF/capturetheflag/assets/28972859/1d76f6e8-2b04-4129-84cb-15d70587d205)

2023-07-08 19:01 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
> It should work now. Is the way I have done the proper way, or is another better way possible?

That works, but are you going to have the same problem further down in the code?

2023-07-09 06:48 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
Everything seems to be fine for the code below since if `hpmarker` is not `true`, it would go to default markers, where it would need to have the marker as pointed and if not pointed than would return false, which would exit the code before any such problem comes to view, isn't it? At least that is what I have understood from the code at present.

2023-07-09 07:48 UTC, src4026 commented
Indentation seems to be bad still. What's wrong with my editor...making changes :+1:

2023-07-09 07:54 UTC, src4026 commented
Done! I realised that the `end` above the next `if` statement messed up the indention whenever I made a newline. Phew

2023-07-09 07:55 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
Ah, so my editor kept adding weird indentations. I kept wondering how it kept going back a tab when I didn't do anything intentionally xD

2023-07-09 10:48 UTC, farooqkz requested changes

2023-07-09 10:48 UTC, farooqkz commented on mods/ctf/ctf_modebase/markers.lua
>  	end
Indents are wrong. You've used 3 spaces instead of a tab

2023-07-09 11:04 UTC, src4026 commented
Hmmm.

2023-07-09 11:39 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
>  	end
Indentation is fixed now?

2023-07-09 11:45 UTC, src4026 commented on mods/ctf/ctf_modebase/markers.lua
>  	end
Are they fixed now?

2023-07-09 15:57 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
>  	end
In VSCode you can run `Ctrl+Shift+P` and run `Convert Indentation to Tabs`

I'll check it when I do cleanup though

2023-07-09 15:58 UTC, LoneWolfHT approved these changes
Looks ok, I'll go through and test/cleanup before merging though

2023-07-09 16:01 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/markers.lua
> +		hpmarker = true
I think you could get a crash if hpmarker is true and pointed_thing is nil. Added a check for that for now, I'll make sure in my cleanup review though

2023-07-10 10:42 UTC, src4026 commented
> @src4026 
> As a programmer/developer, you must learn the tools you use and utilizing them. This includes your Operating System, your web browser and finally... your development environment. You must learn about your development environment enough to have control over it. And you must know exactly what are you doing with it. Like what will happen if you use X key combination. You also have freedom to choose your tools. If you are not fine with an editor or IDE you use because it has bugs or the UI it has does not suit you, feel free to try another one.
> 
> For instance, I want everything to be done with my keyboard. I am not comfortable with mouse unless it can really do the job much better than a keyboard(like playing Minetest!). Therefore, I use i3 WM to switch quickly between open windows. And I use vim which its philosophy is no mouse.

I have been having a long journey of changing IDEs, and making this PR is in the middle of it, thus this chaos. I have been trying to find the editor that truly is the one I can find, andI did find it. But due to my current software conflicts, I am unable to use it, that is, Doom Emacs. I had to use VSCodium for the time being but decided to move to something else. I then chose Neovim's NvChad for a start. (I had used Neovide prior to this but due to the limitations of the apt repository, some packages were outdated). When I used nvim, the lua linter was fantastic! But the way it handled tabs was extremely weird, which happened to be the case here. I am using VSCodium at the moment with the Lua Language server installed, but the linter is something I haven't been able to figure out. Could anyone please help me with it?

2023-07-10 10:43 UTC, src4026 commented
> > @src4026 
> > As a programmer/developer, you must learn the tools you use and utilizing them. This includes your Operating System, your web browser and finally... your development environment. You must learn about your development environment enough to have control over it. And you must know exactly what are you doing with it. Like what will happen if you use X key combination. You also have freedom to choose your tools. If you are not fine with an editor or IDE you use because it has bugs or the UI it has does not suit you, feel free to try another one.
> > 
> > For instance, I want everything to be done with my keyboard. I am not comfortable with mouse unless it can really do the job much better than a keyboard(like playing Minetest!). Therefore, I use i3 WM to switch quickly between open windows. And I use vim which its philosophy is no mouse.
> 
> I have been having a long journey of changing IDEs, and making this PR is in the middle of it, thus this chaos. I have been trying to find the editor that truly is the one I can find, andI did find it. But due to my current software conflicts, I am unable to use it, that is, Doom Emacs. I had to use VSCodium for the time being but decided to move to something else. I then chose Neovim's NvChad for a start. (I had used Neovide prior to this but due to the limitations of the apt repository, some packages were outdated). When I used nvim, the lua linter was fantastic! But the way it handled tabs was extremely weird, which happened to be the case here. I am using VSCodium at the moment with the Lua Language server installed, but the linter is something I haven't been able to figure out. Could anyone please help me with it? 

Also, I do understand the freedom and have much explored with my forage on Linux. Everything I use has something to it. Thank you for reminding me :)

2023-07-12 15:28 UTC, farooqkz commented
@src4026 Please do re-base only on request. It is annoying to have notifications for the repo watchers just for unnecessary rebases.

2023-07-12 15:30 UTC, src4026 commented
> @src4026 Please do re-base only on request. It is annoying to have notifications for the repo watchers just for unnecessary rebases.

Oh sorry. I didn't know it was sent to watchers.

2023-07-26 16:53 UTC, LoneWolfHT commented
There's no rule against it or anything, but it annoys people that like an empty notification queue :P

I usually commit the rebase without pushing it. That way I get my rebase locally and it'll show up on the repo whenever I push other changes that watchers might be more interested in

2023-07-29 15:07 UTC, LoneWolfHT requested changes
* Need to remove the `[]` around the numbers in the HP markers.
* Markers should also show HP of marked players if they're not full health

2023-08-18 21:47 UTC, sonicSMASH commented
How about an additional argument that specifies which player to show it to (like /mp <player>)

2023-08-19 04:35 UTC, src4026 commented
> How about an additional argument that specifies which player to show it to (like /mp <player>)
>  

I didn't understand what you meant by this. Could you elaborate please?

2023-08-19 23:53 UTC, sonicSMASH commented
> > How about an additional argument that specifies which player to show it to (like /mp )
> 
> I didn't understand what you meant by this. Could you elaborate please?

The command /mp allows a marker to be placed, but it's only visible to the player added after the command. You could implement this into the HP markers so that everyone on your team doesn't need to see it.

2023-08-20 04:44 UTC, src4026 commented
> > > How about an additional argument that specifies which player to show it to (like `/mp` )
> > 
> > I didn't understand what you meant by this. Could you elaborate please?
> 
> The command `/mp` allows a marker to be placed, but it's only visible to the player added after the command. You could implement this into the HP markers so that everyone on your team doesn't need to see it.

Ah, then I suppose it could be good as well. What are your thoughts on this @farooqkz and @LoneWolfHT ?

2023-08-21 16:56 UTC, LoneWolfHT commented
Maybe to all medics in your team. But that should be done in another PR if you want

2023-08-21 17:04 UTC, LoneWolfHT approved these changes

2023-08-21 17:05 UTC, merged