Add a list containing fall damage factors
MT-CTF/capturetheflag pull request #1167
Opened 2023-07-02 03:53 UTC by FlamingRCCars

This is a basic mod that allows you to individually set the fall damage factors of each block, I have 2 example values in here, but they can be changed. 

Voted 14-1 on CTF suggestions channel
https://discord.com/channels/447819017391046687/448136308108296213/1124496383634833509

2023-07-02 11:12 UTC, farooqkz commented
Related: https://discord.com/channels/447819017391046687/1008040841102766153/1124616741268496416

2023-07-02 11:33 UTC, farooqkz commented
Shouldn't this be in `mtg/ctf_changes`? ping @LoneWolfHT

2023-07-02 14:34 UTC, LoneWolfHT commented
Yeah, if you don't mind creating a second file for your mod in there, or just adding the code to the already existing init.lua

2023-07-02 14:43 UTC, FlamingRCCars commented
@LoneWolfHT Changes merged, should be good now.

2023-07-02 14:55 UTC, farooqkz approved these changes
The code LGTM but unsure about the value of damage.

2023-07-02 14:56 UTC, FlamingRCCars commented
Yep, those values are temporary place holders

2023-07-03 19:52 UTC, LoneWolfHT requested changes

2023-07-03 19:52 UTC, LoneWolfHT commented on mods/mtg/ctf_changes/init.lua
> +    {"default:snowblock", -14}, -- From a height of 13 blocks you take 5 damage
This could be `["default:snowblock"] = -14,` and all other table elements could follow the same pattern

2023-07-03 19:52 UTC, LoneWolfHT commented on mods/mtg/ctf_changes/init.lua
> +    for _, entry in ipairs(node_fall_damage_factors) do
You could then change this to
`for nodename, reduction in ipairs(node_fall_damage_factors) do`

2023-07-04 11:52 UTC, farooqkz commented on mods/mtg/ctf_changes/init.lua
> +    for _, entry in ipairs(node_fall_damage_factors) do
Why `pairs` instead of `ipairs` here?

2023-07-04 16:50 UTC, LoneWolfHT commented on mods/mtg/ctf_changes/init.lua
> +    for _, entry in ipairs(node_fall_damage_factors) do
`ipairs` can only loop over lists, in lists the keys are `1, 2, 3, 4, ...`, but I changed the table we're looping over to use named keys, which makes it into a normal table, not a list table. `pairs` loops over both lists and normal tables

2023-07-04 16:51 UTC, LoneWolfHT approved these changes

2023-07-04 16:52 UTC, merged