Add Death Message
MT-CTF/capturetheflag pull request #1179
Opened 2023-07-11 19:02 UTC by 165135

Send death message to a player after they die telling them who killed them and who assisted in the kill. Can be toggled on and off in the Inventory Settings tab.

2023-07-11 19:11 UTC, farooqkz commented
You are doing well young programmer ;)

2023-07-11 22:51 UTC, 165135 commented
I did not know that #n puts the PR link and name... I know now XD

2023-07-12 02:02 UTC, LoneWolfHT reviewed
This should probably be made into a part of features.lua, as it's not a part of the kill list, and is basically just sending a chat message

2023-07-12 04:08 UTC, 165135 commented
![image](https://github.com/MT-CTF/capturetheflag/assets/102005519/60db1c32-a3b8-479a-96c7-c7ef4d568ac5)
For some reason, its showing the setting multiple times

2023-07-12 05:59 UTC, 165135 commented on mods/ctf/ctf_combat/ctf_death_message/init.lua
> +minetest.register_on_mods_loaded(function()
didn't need too, was extra copied from elsewhere

2023-07-12 06:03 UTC, 165135 commented
Okay, I think the three time setting register is part of a bigger problem that functions.lua is somehow running 3 times, possibly
![image](https://github.com/MT-CTF/capturetheflag/assets/102005519/6443d287-dd1e-4d76-8d56-98a96f63a011)

2023-07-12 07:12 UTC, 165135 commented
Oh I'm silly its called from the three gamemode init.luas

2023-07-14 06:09 UTC, 165135 commented
@farooqkz Did I miss something that needed to be changed?

2023-07-14 07:59 UTC, farooqkz commented
> @farooqkz Did I miss something that needed to be changed?

Just tested. It's almost okay. There is a small typo which I'm gonna make suggestion for it. after you committed my suggestion, I will mark it as ready for review.

2023-07-14 08:03 UTC, farooqkz requested changes

2023-07-14 08:04 UTC, farooqkz commented
@LoneWolfHT  I haven't reviewed the code logic yet.

2024-05-20 21:46 UTC, farooqkz commented
@165135 I tested this a long time ago. Does it also say how much score your killer got?

2024-05-20 22:40 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/features.lua
> +    ["fire"] = {"burnt to a crisp"}
```suggestion
    ["grenades_frag"] = {"blown up", "fragged"},
    ["knockback_grenade"] = {"sent flying", "doomed to fall"},
    ["black_hole_grenade"] = {"sucked into the void"},
    ["sword"] = {"killed", "sliced up"},
    ["axe"] = {"killed", "chopped up",},
    ["shovel"] = {"killed with the tool that dug your grave"},
    ["pick"] = {"killed", "mistaken for mese ore"},
    ["ctf_ranged"] = {"shot"},
    ["rifle"] = {"sniped"},
    ["default_water"] = {"drowned", "over-hydrated"},
    ["damage_cobble"] = {"mined a little too much damage cobble"},
    ["lava"] = {"tried to swim in lava", "took a hot bath"},
    ["fire"] = {"burnt to a crisp"},
```

2024-05-20 22:41 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/features.lua
> +})
```suggestion

ctf_settings.register("send_death_messages", {
    type = "bool",
    label = "Receive death messages.",
    description = "When enabled, you will receive a death message whenever you die stating who killed you.",
    default = "true",
})
```

2024-06-26 19:17 UTC, LoneWolfHT commented
What do you think about also showing how many points were given for killing you? https://discord.com/channels/447819017391046687/1008040841102766153/1218686930833768612
```
Suggestion: On the death screen, show "<player_name> killed you for <points> points!"
```

2024-06-26 19:28 UTC, LoneWolfHT commented
Oh, I guess #1306 already does that

2025-05-16 17:36 UTC, merged