add bonus for killing a flag carrier
MT-CTF/capturetheflag pull request #1180
Opened 2023-07-12 04:30 UTC by lazylier

This is supposed to multiply the kill score by 1 + .25 for each flag held by the victim.

2023-07-12 10:22 UTC, farooqkz requested changes

2023-07-12 10:22 UTC, farooqkz commented on mods/ctf/ctf_modebase/features.lua
> +		if p.p == player then
Use a better variable name than `p`

2023-07-12 10:22 UTC, farooqkz commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier + .25
```suggestion
			flag_multiplier = flag_multiplier + 0.25
```

Because it's easier to read

2023-07-13 09:46 UTC, farooqkz commented
@lazylier For the next time, you can simply commit my suggestion from Github UI.

@LoneWolfHT looks good to me. Except that the multiplier could be further discussed.

2023-07-26 16:47 UTC, LoneWolfHT approved these changes

2023-07-26 16:47 UTC, LoneWolfHT commented
This can be merged when I reset ranks on August 16

2023-07-28 18:20 UTC, LoneWolfHT commented
This doesn't benefit from a testing session, as it's pretty simple

2023-08-19 18:33 UTC, merged