Add medic flag taking
MT-CTF/capturetheflag pull request #1182
Opened 2023-07-13 05:32 UTC by 165135

Adds clicking flag with bandage takes/captures a flag.
(I wouldn't be surprised if this is a wrong and inefficient way to do it)

2023-07-13 09:52 UTC, farooqkz requested changes

2023-07-13 09:52 UTC, farooqkz commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    end
```suggestion
			    hp = math.min(hp + hp_add, limit)
```

2023-07-13 09:55 UTC, farooqkz commented
@LoneWolfHT  LGTM

2023-07-13 16:16 UTC, 165135 commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    end
I didn't really mess with this part but sure

2023-07-14 02:58 UTC, farooqkz commented
@165135 As I said somewhere else, you could simply commit my suggestion from Github UI rather than making your own commit.

2023-07-14 06:05 UTC, 165135 commented
Wasn't sure, got it :+1:

2023-07-14 21:41 UTC, LoneWolfHT commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    local result = RunCallbacks(ctf_healing.registered_on_heal, player, object, hp_add)
hp_add isn't always accurate when passed to the registered_on_heal callbacks

2023-07-14 21:43 UTC, LoneWolfHT commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +                local node_above = minetest.get_node(node_above_pos)
```suggestion
                local node_pointed = minetest.get_node(pointed_thing.under)
                local node_above = minetest.get_node(pointed_thing.under:offset(0, 1, 0))
```

2023-07-15 00:38 UTC, 165135 commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    local result = RunCallbacks(ctf_healing.registered_on_heal, player, object, hp_add)
![image](https://github.com/MT-CTF/capturetheflag/assets/102005519/0fc332f5-f867-4631-93c9-9e58dea02361)
I didn't change the bandage healing code except for this edit that @farooqkz suggested

2023-07-26 16:31 UTC, LoneWolfHT commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    local result = RunCallbacks(ctf_healing.registered_on_heal, player, object, hp_add)
@farooqkz Can you see what functionality you removed with that suggestion?

2023-07-31 05:10 UTC, 165135 commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    local result = RunCallbacks(ctf_healing.registered_on_heal, player, object, hp_add)
@LoneWolfHT I could just put it back the way it was and not worry about it

2023-08-03 15:29 UTC, farooqkz commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +                    end
```suggestion
                local node_pointed = minetest.get_node(pointed_thing.under)
                local node_above = minetest.get_node(pointed_thing.under:offset(0, 1, 0))
                local flag_captured_top = "ctf_modebase:flag_captured_top"
                if node_pointed.name ~= "ctf_modebase:flag_captured_top" then
                    if node_pointed.name:find("ctf_modebase:flag_") then
		                ctf_modebase.flag_on_punch(player, pointed_thing.under, node_pointed)
                    elseif node_above.name:find("ctf_modebase:flag_") and node_above.name ~= flag_captured_top then
                        ctf_modebase.flag_on_punch(player, pointed_thing.under:offset(0, 1, 0), node_above)
                    end
```

It was crashing when the flag was taken and the bottom was clicked with medic's bandage. This fixes it.

2023-08-10 21:27 UTC, LoneWolfHT commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +			    local result = RunCallbacks(ctf_healing.registered_on_heal, player, object, hp_add)
:+1: It's just something they could learn a little from

2023-08-14 01:48 UTC, LoneWolfHT commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +                local flag_captured_top = "ctf_modebase:flag_captured_top"
This variable isn't needed

2023-08-15 02:42 UTC, 165135 commented on mods/ctf/ctf_combat/ctf_healing/bandage.lua
> +                local flag_captured_top = "ctf_modebase:flag_captured_top"
Removed ``flag_captured_top``, I think that's what you meant

2023-08-21 18:18 UTC, merged