Fix poison nades disappearing
MT-CTF/capturetheflag pull request #1183
Opened 2023-07-13 05:55 UTC by 165135

Drop all items before respawn to clear bugged poison smoke nades in inventory if they are thrown near enemy base and then the player dies before they land.

2023-07-13 09:38 UTC, farooqkz requested changes
Not sure it's the best solution but I guess it works anyway. You should add the mod `dropondie` to dependencies of `ctf_modebase` in `mod.conf`

2023-07-13 17:57 UTC, 165135 commented
> Not sure it's the best solution but I guess it works anyway. You should add the mod `dropondie` to dependencies of `ctf_modebase` in `mod.conf`

![image](https://github.com/MT-CTF/capturetheflag/assets/102005519/e6ccead9-12d7-48e9-8f02-f3b2a05ca3f0)
I'm not familiar with dependencies, but it causes an error, maybe because dropondie has ctf_modebase as a dependency also

2023-07-13 20:49 UTC, 165135 commented
Well, at least now it won't _crash_

2023-07-14 02:56 UTC, farooqkz commented
> Well, at least now it won't _crash_

If you are making it optional, the code should handle if there is no dropondie.

2023-07-26 16:36 UTC, LoneWolfHT commented
This is a bad approach, `ctf_modebase` shouldn't try to do anything with `dropondie`, it should provide an API that dropondie can use, but that's it.

Try checking player hp when the poison grenade is added back to the players inventory. The hp should be 0 if the player is dead/respawning, so you can just drop the grenade where it landed

2023-08-10 22:11 UTC, LoneWolfHT commented
Probably going to merge https://github.com/MT-CTF/capturetheflag/pull/1201 unless you want a different approach

2023-08-12 20:14 UTC, closed without merging