Disable usage of classes abilities during build time
MT-CTF/capturetheflag pull request #1195
Opened 2023-08-03 00:30 UTC by 165135

Disable all abilities for classes instead of just paxel usage
From suggestion: https://discord.com/channels/447819017391046687/448136308108296213/1135607133661044788

2023-08-03 13:59 UTC, farooqkz requested changes

2023-08-03 13:59 UTC, farooqkz commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		if itemstack:get_wear() == 0 and ctf_modebase.match_started then
This way the player will get the "Can't use during build time" message even when match has started but item's wear is 0.

2023-08-03 13:59 UTC, farooqkz commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		if itemstack:get_wear() == 0 and ctf_modebase.match_started then
Same as L154

2023-08-10 21:30 UTC, LoneWolfHT commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		if itemstack:get_wear() == 0 and ctf_modebase.match_started then
Not fixed

2025-05-16 19:02 UTC, LoneWolfHT commented
I think this has already been done, closing

2025-05-16 19:02 UTC, closed without merging