Adding map duration to `ctf_map` table
MT-CTF/capturetheflag pull request #1221
Opened 2023-08-25 08:02 UTC by src4026

I have tried, but it's probably not how it should be done.

2023-08-25 12:46 UTC, farooqkz commented
What problem does it aim to solve?

2023-08-25 12:56 UTC, src4026 commented
> What problem does it aim to solve?

Right, I should've mentioned that in the OP. I've changed it to be clearer :thumbsup:

2023-08-25 17:35 UTC, LoneWolfHT requested changes

2023-08-25 17:35 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
>  end)
This needs to go to the init.lua
Make sure to set `start_time` to an initial value of false in the `ctf_map` table too, that way people reading the code know it exists

2023-08-25 17:35 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
> +	ctf_map.start_time = nil
Needs to go to the `init.lua`

2023-08-26 18:35 UTC, src4026 commented
Ah, I remember trying to first add start_time to the table, but it didn't work. I was doing something wrong. I have made the commits for it now that it seems to work. I am not able to understand what conflicts my changes are having with the files, could anyone please explain?

2023-08-27 17:12 UTC, src4026 commented
I think the conflicts are now resolved.

2023-08-27 17:24 UTC, src4026 commented
![image](https://github.com/MT-CTF/capturetheflag/assets/129506166/0dc49b83-5d71-4992-a7b5-914183385fcc)
Why is it showing each of the tabs changed, although I didn't seem to have done any change to those lines?

2023-09-06 15:42 UTC, LoneWolfHT requested changes

2023-09-06 15:44 UTC, LoneWolfHT commented
> ![image](https://user-images.githubusercontent.com/129506166/263544245-0dc49b83-5d71-4992-a7b5-914183385fcc.png) Why is it showing each of the tabs changed, although I didn't seem to have done any change to those lines?

It changed from tabs to spaces, you can tell by seeing how your selection jumps across them

2023-09-07 11:27 UTC, src4026 commented on mods/ctf/ctf_map/init.lua
> +    end
Ah, thank you!

2023-09-24 19:10 UTC, LoneWolfHT requested changes

2023-09-24 19:10 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
> +	ctf_map.start_time = nil
Still not moved?

```lua
ctf_api.register_on_match_end(function()
    minetest.after(0, function()
        ctf_map.start_time = nil
    end)
end)
```
(Indentation needs to be converted to tabs)

2023-09-24 19:10 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
> +	ctf_map.start_time = nil
The minetest.after(0) is there so that the code runs close to immediately after all `ctf.register_on_match_end()`s are called

2023-09-24 19:10 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
>  end)
Still not moved?

2023-09-25 03:03 UTC, src4026 commented on mods/ctf/ctf_modebase/summary.lua
>  end)
> Still not moved?

Oh I didn't, my bad. I'll do it when I come back home, my apologies.

2023-09-25 03:05 UTC, src4026 commented on mods/ctf/ctf_modebase/summary.lua
>  end)
Hmm, I've added it to the table, do you mean to delete it from here as it may not be needed?

2023-09-25 05:32 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
>  end)
The whole `register_on_match_start()` section should, only the `ctf_map.get_duration()` function should appear/be used outside of the `init.lua`, and all changes to the start_time variable should be made in the file where it's declared (`init.lua`) due to it being an internal working of `get_duration()`, if that makes sense

2023-09-25 05:33 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/summary.lua
>  end)
No rush/harm done btw :P

2023-10-14 18:06 UTC, LoneWolfHT requested changes

2023-10-14 18:06 UTC, LoneWolfHT commented on mods/ctf/ctf_map/init.lua
> +		local mapDuration =  ctf_map.get_duration()
No check for `false` or `nil`

2023-10-14 18:08 UTC, LoneWolfHT approved these changes
Missing a newline at the end of one of the files, I'll fix when I merge it later otherwise

2023-10-15 02:14 UTC, merged