give way more score for killing a flag thief
MT-CTF/capturetheflag pull request #1302
Opened 2024-06-10 17:26 UTC by farooqkz

- [x] This PR has been tested locally

The suggestion originates from here: https://discord.com/channels/447819017391046687/448136308108296213/1246872747838279710

The flag multiplier which multiplies the score is 1 for no flag, and multiplied by 2 for each flag added. Like 2 for a flag and 4 for two flags. Because it's way harder to not get killed and steal the second flag.

2024-06-10 19:16 UTC, farooqkz commented
Okay... I thought the change is trivial

2024-06-10 19:38 UTC, farooqkz commented
Self review done

2024-06-13 17:51 UTC, LoneWolfHT requested changes

2024-06-13 17:51 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier * 2
I'm pretty sure this is a literal exponential increase. For now I'd suggest this instead:
```suggestion
			flag_multiplier = flag_multiplier + 1
```
That should result in the score being the normal(?) kill score * the number of flags they have, starting at x2 for one flag

2024-06-13 20:19 UTC, farooqkz commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier * 2
Yes it's an exponential increase. Getting flag of one team is not that hard. But getting flag of one team and at the same time getting flag of another one, is extremely hard. You have teammembers of the first team on your tail, everyone know your location every second, and then you have to approach base of another team to get their flag.

Therefore, I think exponential makes perfect sense.

2024-06-13 22:21 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier * 2
The suggestion is trying to encourage people to kill flag carriers, what you're saying is maybe justification for rewarding the flag carrier.

If this score increase isn't enough it could be changed to +2 or more

2024-06-14 12:04 UTC, farooqkz commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier * 2
Maybe put it to a vote among players?

2024-06-14 12:04 UTC, farooqkz commented on mods/ctf/ctf_modebase/features.lua
> +			flag_multiplier = flag_multiplier * 2
Or otherwise ask for a third party opinion. Since I don't agree with you, a third party opinion helps.

2024-07-12 16:33 UTC, LoneWolfHT approved these changes

2024-08-17 18:47 UTC, merged