Change donate command to accept multiple recipients
MT-CTF/capturetheflag pull request #1303
Opened 2024-06-10 22:10 UTC by lazylier

I have tested this about as well as I can think. I do not have the ability to test with more than 2 clients. It might not be written as cleanly as possible, although I've tried.

I've tried to keep flexibility with the order of parameters. Player names are checked for validity until there is at least one valid player name and a score amount, after which all remaining text is assumed to be the donation message.

[suggestion here](https://discord.com/channels/447819017391046687/448136308108296213/1249032532847099944)
- [x] This PR has been tested locally

2024-06-14 17:09 UTC, LoneWolfHT requested changes

2024-06-14 17:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/ranking_commands.lua
> +		end
- This should be a `for pname, team in pairs(pnames) do`

- It might be faster to take `score_total` from the player donating before the loop, instead of running it multiple times.

- As for strings like `names`, I'd prefer to just do `names = names .. pname .. ", "` and `string:sub(1, -3)` after the loop to remove the trailing `", "`

2024-06-14 17:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modebase/ranking_commands.lua
> +				dmessage = dmessage .. " " .. p
Why is the list (table) size of a string being counted?

2024-06-15 17:51 UTC, lazylier commented on mods/ctf/ctf_modebase/ranking_commands.lua
> +				dmessage = dmessage .. " " .. p
> Why is the list (table) size of a string being counted?

That is because as soon as the message is started all subsequent words are assumed to be part of the message, so not to be checked for being score or player names.

2024-06-29 16:15 UTC, LoneWolfHT approved these changes

2024-06-29 16:20 UTC, merged