Update nodes.lua
MT-CTF/capturetheflag pull request #1327
Opened 2024-07-14 13:01 UTC by qasdwer01

Fix spammed messages sent to player when adding an item into treasure chest using Shift+ Item

- [ ] This PR has been tested locally

2024-07-24 05:12 UTC, farooqkz commented
Hello. Thanks for your interest in contributing to CTF. Please update the PR title with a better more descriptive name. Also I am in favor of removing this message from chat and sending as HUD event message, instead. @LoneWolfHT Opinion(s)?

2024-07-25 18:36 UTC, LoneWolfHT commented
hud messages would be hidden by the formspec, the chat gives you a better chance of seeing what went wrong.

2024-07-25 18:37 UTC, LoneWolfHT requested changes

2024-12-02 21:33 UTC, LoneWolfHT commented
Are you still interested in finishing this PR or do you want someone to take it over?

2024-12-06 22:54 UTC, LoneWolfHT commented
Got answer via Discord, this PR is up for adoption

2025-05-16 16:58 UTC, LoneWolfHT commented
https://github.com/MT-CTF/capturetheflag/commit/dbe1bead1e531f6456ac93e93936673e4819abb5

2025-05-16 16:58 UTC, closed without merging