Hobbit
MT-CTF/capturetheflag pull request #1331
Opened 2024-07-21 20:19 UTC by pl608

Allows external mods to make changes to the player model
don't know if this will work on more advanced models
also don't know if this was necessary however it works and that is all I was shooting for :)
- [x] This PR has been tested locally

2024-07-21 20:38 UTC, LoneWolfHT commented
Just have your mod edit the animations in `player_api.registered_models["character.b3d"]` after depending on the `ctf_player` mod, no need for a setting or completely replacing the CTF model

2024-07-21 20:40 UTC, pl608 commented
ok. Though the classes update that I added will be needed since otherwise it will be a normal sized player anytime someone is a knight or scout (and potentially medic too)

2024-07-25 18:09 UTC, LoneWolfHT requested changes

2024-07-25 18:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		visual_size =  vector.new(0.1, 0.05, 0.1),
```suggestion
		visual_size = vector.new(0.1, 0.05, 0.1),
```

2024-07-25 18:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		visual_size =  vector.new(-0.1, 0.0, -0.1),
```suggestion
		visual_size = vector.new(-0.1, 0.0, -0.1),
```

2024-07-25 18:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +	local base_size = vector.new(player_api.registered_models['character.b3d'].visual_size)
Why is vector.new() used here?

2024-07-25 18:09 UTC, LoneWolfHT commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +		visual_size = vector.add(base_size,class.visual_size ) or base_size
```suggestion
		visual_size = vector.add(base_size, class.visual_size) or base_size
```

2024-07-25 18:10 UTC, LoneWolfHT commented
You can just commit all those suggestions, I put them there so you can see how I prefer code style

2024-07-27 02:36 UTC, pl608 commented on mods/ctf/ctf_modes/ctf_mode_classes/classes.lua
> +	local base_size = vector.new(player_api.registered_models['character.b3d'].visual_size)
because it was used somewhere else and I didn't want to break anything

2024-08-08 18:00 UTC, merged

2024-08-08 19:11 UTC, LoneWolfHT commented
@pl608 Instant crash on server start, I thought you tested this locally?

2024-08-08 20:03 UTC, pl608 commented
what was the error? I never had an issue with and without my mod