Few Redef Mod Fixes
MT-CTF/capturetheflag pull request #1365
Opened 2024-12-09 06:25 UTC by mrtechtroid

- [x] This PR has been tested locally
- Revert max stack size update from 100 to 99. 
- Make all the ladders 3d textured. (Instead of only default one's)

2024-12-09 14:34 UTC, farooqkz requested changes

2024-12-09 14:34 UTC, farooqkz commented on mods/mtg/redef/redefinitions/3d_ladders.lua
>  for l,def in pairs(ladders) do
```suggestion
for _idx, def in ipairs(ladders) do
```

2024-12-09 16:21 UTC, LoneWolfHT commented
settingstype.txt doesn't set defaults, I commented out the code for stack changes in the init.lua

2024-12-14 00:10 UTC, LoneWolfHT approved these changes

2024-12-14 00:11 UTC, merged