Disable build-where-somebody-stands serverside
MT-CTF/capturetheflag pull request #698
Opened 2020-10-30 17:59 UTC by appgurueu

Counters pillaring.

2020-10-30 18:11 UTC, Panquesito7 requested changes

2020-10-30 18:11 UTC, Panquesito7 commented on mods/pvp/antipillar/init.lua
> +local visualize_box
```suggestion
-- Capture The Flag mod: antipillar

local visualize_box
```

2020-10-30 18:11 UTC, Panquesito7 commented on mods/pvp/antipillar/test.lua
> +return visualize_box
```suggestion
return visualize_box

```

2020-10-30 18:11 UTC, Panquesito7 commented on mods/pvp/antipillar/mod.conf
> +description = Prevents pillaring by not allowing players to build where they stand
```suggestion
description = Prevents pillaring by not allowing players to build where they stand

```

2020-10-30 18:11 UTC, Panquesito7 commented on mods/pvp/antipillar/init.lua
> +end)
```suggestion
end)

```

2020-10-30 18:31 UTC, appgurueu commented
@Panquesito7 I don't like that code style. The "Ctf mod" comment adds almost nothing, the additional line breaks are unneeded on modern systems. Is this the accepted code style?

2020-10-30 18:38 UTC, appgurueu commented on mods/pvp/antipillar/init.lua
> +visualize_box = loadfile(minetest.get_modpath(minetest.get_current_modname()) .. "/test.lua")()
Currently uncommented, I will comment this again on merge

2020-11-20 15:56 UTC, appgurueu commented
Also see https://content.minetest.net/packages/LMD/disable_build_where_they_stand/

2021-05-19 15:56 UTC, closed without merging