Add Team K/D to summary
MT-CTF/capturetheflag pull request #702
Opened 2020-11-16 15:56 UTC by Axaxax88

These changes will add "Team K/D" to summary counted from red and blue kills and deaths.

2020-11-16 16:04 UTC, LoneWolfHT commented
We want a newline at the end of every file FYI

2020-11-16 16:05 UTC, Axaxax88 commented
"We want a newline at the end of every file FYI"
I don't understand, I'm newb.

2020-11-16 16:06 UTC, LoneWolfHT requested changes
> "We want a newline at the end of every file FYI"
> I don't understand, I'm newb.

Your last commit removed the newline at the end of the file. Could you add it back?

2020-11-16 16:06 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +    end
This `end` is indented with spaces instead of tabs. Same for the one below it

2020-11-16 16:06 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
![image](https://user-images.githubusercontent.com/28972859/99277274-7a20e380-27e2-11eb-8b31-6649423e7501.png)

2020-11-16 16:09 UTC, Axaxax88 commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
Okay, okay, okay, I'll try to repair it all...

2020-11-16 16:11 UTC, Axaxax88 commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
Can I give it up - next to "kills"?

2020-11-16 16:14 UTC, winniepee commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
just remove "Teams K/D"

2020-11-16 16:14 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
Might be best to increase the formspec height, move everything below the 'Flag captured by...' line down a bit, then put the team KD down on a third line

2020-11-16 16:14 UTC, Axaxax88 commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
![screenshot_20201116_171339](https://user-images.githubusercontent.com/74550391/99278335-330d0f80-282f-11eb-9a6b-2172efdda839.png)

2020-11-16 16:18 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
That might work actually

2020-11-16 16:19 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +	ret = ret .. "label[5,0.5;" .. minetest.colorize(red.color, tostring(red_kd))
Guess that could work too

2020-11-16 16:38 UTC, Axaxax88 commented
Done, I repaired it yet.

2020-11-23 22:14 UTC, LoneWolfHT commented
![image](https://user-images.githubusercontent.com/28972859/100021311-27bd6500-2d96-11eb-978c-1e98effe4362.png)

2020-11-23 22:17 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/gui.lua
> +	end
This `end` and the one above it still aren't fixed. It looks like you just removed the indentation?
![image](https://user-images.githubusercontent.com/28972859/100021579-8edb1980-2d96-11eb-96a5-bb480d432838.png)

2020-11-24 20:45 UTC, LoneWolfHT approved these changes
Merged with the syntax fixes

2020-11-24 20:45 UTC, closed without merging