Add antisabotage mod
MT-CTF/capturetheflag pull request #725
Opened 2020-12-23 21:43 UTC by TSafa-23

Prevents players of the same team from mining under or (somewhat) near others. Even works whilst crouching.

2020-12-23 22:07 UTC, LoneWolfHT requested changes

2020-12-23 22:07 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +					if math.floor(player_pos.x+1.5) >= pos.x and pos.x >= math.floor(player_pos.x-.5) and math.floor(player_pos.z+1.5) >= pos.z and pos.z >= math.floor(player_pos.z-.5) then
`vector.distance(v1, v2)` may work best here

2020-12-23 22:07 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +	minetest.chat_send_player(digger:get_player_name(), "You may not mine blocks under where your teammates are near!")
"You can't mine blocks under your teammates!" would probably be easier to follow

2020-12-23 22:08 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +function myFunc(pos, oldnode, digger) --this is your local neighborhood uwu. Say hello!
Oh, and this could be `preventTeamGrief()`

2020-12-23 22:10 UTC, LoneWolfHT commented
How does this work with doors?
You might want to look into catching griefing before the block is dug instead. Via minetest.is_protected() or something

2020-12-23 22:37 UTC, TSafa-23 commented
Typically I would prefer to see before the block is dug as well, however this works well and I haven't ran into any issues with it yet.

It works with doors without issue, which includes opening/closing and breaking them.

2020-12-24 05:37 UTC, Panquesito7 commented on mods/pvp/antisabotage/init.lua
> +function preventTeamGrief(pos, oldnode, digger) -- better function names, distance calculations, and message suggested by Lone_Wolf.
```suggestion
-- Capture the Flag mod: antisabotage

function preventTeamGrief(pos, oldnode, digger) -- better function names, distance calculations, and message suggested by Lone_Wolf.
```

2020-12-24 05:37 UTC, Panquesito7 commented on mods/pvp/antisabotage/mod.conf
> +depends = ctf, ctf_classes
Maybe add a description?

2020-12-24 14:25 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +function preventTeamGrief(pos, oldnode, digger) -- better function names, distance calculations, and message suggested by Lone_Wolf.
Already the modname with ctf being mentioned in depends.txt.

2020-12-24 14:31 UTC, TSafa-23 commented on mods/pvp/antisabotage/mod.conf
> +depends = ctf, ctf_classes
See [https://github.com/MT-CTF/capturetheflag/pull/725/commits/e881adafc12bd791950c463ead2c46dc71045715](url)

2020-12-24 17:17 UTC, TSafa-23 commented on mods/pvp/antisabotage/mod.conf
> +depends = ctf, ctf_classes
Finished

2020-12-24 17:17 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +					if math.floor(player_pos.x+1.5) >= pos.x and pos.x >= math.floor(player_pos.x-.5) and math.floor(player_pos.z+1.5) >= pos.z and pos.z >= math.floor(player_pos.z-.5) then
Done, now much shorter and easier to read. Thanks for the suggestion!

2020-12-24 17:17 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +	minetest.chat_send_player(digger:get_player_name(), "You may not mine blocks under where your teammates are near!")
Agreed, added.

2020-12-24 17:18 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +function myFunc(pos, oldnode, digger) --this is your local neighborhood uwu. Say hello!
Function name changed to that for readability

2020-12-24 17:39 UTC, LoneWolfHT requested changes

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +				end
That first `if` (The one with math.floor) can be removed

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/mod.conf
> +depends = ctf, ctf_classes
ctf_classes dependency no longer needed

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +	for _, player in ipairs(minetest.get_connected_players()) do
`ipairs` isn't necessary here and IIRC `pairs` is slightly faster

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +		if not player:is_player() then return end
This check isn't needed. Player will definitely be a player

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +		local name = player:get_player_name()
You could probably create a var for the digger name too as you also use it more than once

2020-12-24 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +				end
With that done you can also get rid of the player_pos variable since it'll only be used once AFAICS

2020-12-24 18:05 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +				end
This has been left unchanged after testing, this is required so you may only be prohibited from mining blocks from under the player instead of around (having this the other way around could wreak havoc in tunneling maps :P)

2020-12-24 18:07 UTC, TSafa-23 commented on mods/pvp/antisabotage/mod.conf
> +depends = ctf, ctf_classes
Fixed.

2020-12-24 18:07 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +	for _, player in ipairs(minetest.get_connected_players()) do
Done.

2020-12-24 18:07 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +		if not player:is_player() then return end
Alright, thanks. :+1:

2020-12-24 18:08 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +		local name = player:get_player_name()
Done.

2020-12-25 04:56 UTC, LoneWolfHT approved these changes
I uh, got carried away with my latest review

2020-12-25 04:56 UTC, LoneWolfHT commented
Merging tomorrow

2020-12-25 06:22 UTC, Panquesito7 commented on mods/pvp/antisabotage/readme.txt
> +# Anti Sabotage
IMHO this file should be in Markdown.

2020-12-25 06:22 UTC, Panquesito7 commented on mods/pvp/antisabotage/init.lua
> +-- Code by Apelta. Mutelated by Lone_Wolf
```suggestion
-- Capture the Flag mod: antisabotage
-- Code by Apelta. Mutelated by Lone_Wolf
```

2020-12-25 13:11 UTC, TSafa-23 commented on mods/pvp/antisabotage/readme.txt
> +# Anti Sabotage
Doesn't need to

2020-12-25 13:12 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +-- Code by Apelta. Mutelated by Lone_Wolf
nah, it's perfect the way it is

2020-12-25 18:36 UTC, merged

2020-12-25 19:23 UTC, Panquesito7 commented on mods/pvp/antisabotage/license.txt
> +Copyright 2020 Apelta
```suggestion
Copyright (C) 2020 Apelta, the MIT license
```