Added web and quicksand to slow players down
MT-CTF/capturetheflag pull request #727
Opened 2020-12-30 19:26 UTC by realOneplustwo

2020-12-30 20:37 UTC, Thomas--S commented
Please remember to provide appropriate license information. Usually, the license is stated in the README files.
You might also want to think about the naming of the mod; the technical modname doesn't match the directory name at the moment.

2020-12-31 23:36 UTC, realOneplustwo commented
Ha, I forgot to rename the modname after I changed the location, fixed.

2020-12-31 23:44 UTC, realOneplustwo commented
Also, what do you mean license information?

2021-01-04 03:46 UTC, TSafa-23 commented
MIT, LGPL, WTFPL, or some other form. MIT will typically be a solid choice for most additions to CTF as there is very little, if any, conflict.

2021-01-04 06:01 UTC, Panquesito7 reviewed
Maybe provide a `README.md` specifying what the mod does, the mod author, and the mod license. 🙂
Also, the texture names should always start with the mod name (e.g.: `slower_cobweb.png`).

2021-01-04 06:01 UTC, Panquesito7 commented on mods/other/slower/init.lua
> +minetest.register_node("slower:cobweb", {
```suggestion
-- Capture the Flag mod: slower
minetest.register_node("slower:cobweb", {
```

2021-01-04 15:52 UTC, TSafa-23 commented on mods/other/slower/mod.conf
> +depends = physics
Btw, this is just a newline in case you were wondering what the actual change was here

2021-01-04 21:56 UTC, Panquesito7 commented on mods/other/slower/mod.conf
> +depends = physics
Exactly: this is because some IDE's have endline as `lf`. It will also remove the ⛔ sign. 😉

2021-01-05 01:27 UTC, realOneplustwo commented on mods/other/slower/init.lua
> +minetest.register_node("slower:cobweb", {
What's the point of that comment?

2021-01-05 02:12 UTC, Panquesito7 commented on mods/other/slower/init.lua
> +minetest.register_node("slower:cobweb", {
IMHO, it makes it look more user-friendly. 🙂

2021-01-05 17:24 UTC, LoneWolfHT requested changes
This has mixed indentation. If you're using VSCode you can fix that by doing:
`Ctrl+Shift+P` then finding the `Convert Indentation to Tabs` command

2021-01-05 21:43 UTC, Thomas--S commented
I'd suggest you to add a media license for the textures.

MIT license is a rather uncommon license choice for texture files.

Please note: I am not a lawyer.

2021-01-06 02:38 UTC, Panquesito7 commented on mods/other/speed_nodes/LICENSE
> +Attribution 4.0 International (CC BY 4.0)
IMHO CC BY-SA 4.0 is better.

2021-01-06 03:42 UTC, LoneWolfHT commented on mods/other/speed_nodes/init.lua
> +		end
Unless I'm missing something these will be run every 0.1 seconds. That's probably not as efficient as it should be

2021-01-06 03:42 UTC, LoneWolfHT commented on mods/other/speed_nodes/LICENSE
> +Attribution 4.0 International (CC BY 4.0)
It'll still work though if they don't care about Sharing Alike

2021-01-06 16:46 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
Efficient? Should it be run faster or slower?

2021-01-06 17:12 UTC, LoneWolfHT commented on mods/other/speed_nodes/init.lua
> +		end
You should only run `physics.set/remove()` if you need to

2021-01-06 17:25 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
Ah, ok.

2021-01-06 17:27 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
The problem is the table "players" in physics/init.lua is local, so I can't access it and check if a key exists in it. Maybe I should edit physics/init.lua as well?

2021-01-06 19:40 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
```suggestion
		if node_below.name == "speed_nodes:quicksand" then
			if players["quicksand"] == nil then
				physics.set(name, "quicksand", asphalt_modifier)
			end
		else
			if players["quicksand"] ~= nil then
				physics.remove(name, "quicksand")
			end
		end

		if node_below.name == "speed_nodes:asphalt" then
			if players["asphalt"] == nil then
				physics.set(name, "asphalt", asphalt_modifier)
			end
		else
			if players["asphalt"] ~= nil then
				physics.remove(name, "asphalt")
			end
		end

		if node_feet.name == "speed_nodes:cobweb" or node_head.name == "speed_nodes:cobweb" then
			if players["cobweb"] == nil then
				physics.set(name, "cobweb", cobweb_modifier)
			end
		else
			if players["cobweb"] ~= nil then
				physics.remove(name, "cobweb")
			end
		end
```
Would something like this work? (After making 'players' public of course.)

2021-01-06 19:42 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
Oh whoops, made a mistake.

2021-01-06 19:43 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
```suggestion
		if node_below.name == "speed_nodes:quicksand" then
			if players[name]["quicksand"] == nil then
				physics.set(name, "quicksand", asphalt_modifier)
			end
		else
			if players[name]["quicksand"] ~= nil then
				physics.remove(name, "quicksand")
			end
		end

		if node_below.name == "speed_nodes:asphalt" then
			if players[name]["asphalt"] == nil then
				physics.set(name, "asphalt", asphalt_modifier)
			end
		else
			if players[name]["asphalt"] ~= nil then
				physics.remove(name, "asphalt")
			end
		end

		if node_feet.name == "speed_nodes:cobweb" or node_head.name == "speed_nodes:cobweb" then
			if players[name]["cobweb"] == nil then
				physics.set(name, "cobweb", cobweb_modifier)
			end
		else
			if players[name]["cobweb"] ~= nil then
				physics.remove(name, "cobweb")
			end
		end
```

2021-01-06 23:52 UTC, LoneWolfHT commented on mods/other/speed_nodes/init.lua
> +		end
```lua
if node_feet.name == "speed_nodes:cobweb" then
    if not players[name].cobweb then
        -- set physics and players[name].cobweb
    end
elseif players[name].cobweb then
    -- unset physics and players[name].cobweb
end
```

Also: What happens if your feet are on asphalt and your head is in a cobweb?

2021-01-07 17:07 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +		end
Both effects get applied?

2021-01-07 22:28 UTC, LoneWolfHT commented on mods/other/speed_nodes/init.lua
> +		end
Looks like I misread the code. Nevermind on that

2021-01-10 23:31 UTC, realOneplustwo commented
Redoing this pull request.

2021-01-10 23:31 UTC, closed without merging