Fix crucial bugs with antisabotage
MT-CTF/capturetheflag pull request #731
Opened 2021-01-04 15:43 UTC by TSafa-23

Fix possible crashes, infinite items, and any related issues

2021-01-04 17:37 UTC, TSafa-23 commented
Now fixed paxel and pillar destroying

2021-01-05 00:44 UTC, Panquesito7 commented on mods/pvp/antisabotage/init.lua
> +
```suggestion
```

2021-01-05 17:39 UTC, LoneWolfHT requested changes

2021-01-05 17:39 UTC, LoneWolfHT commented on mods/pvp/antisabotage/init.lua
> +function isSabotage(pos, oldnode, digger) -- used for paxel, hence why it is now a separate function
This should be renamed to `antisabotage.is_sabotage()`. You will need to create a global table at the top of the file too
(`antisabotage = {}`)

2021-01-05 21:27 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +function isSabotage(pos, oldnode, digger) -- used for paxel, hence why it is now a separate function
Alright, will do in a few minutes

2021-01-06 00:37 UTC, Panquesito7 requested changes

2021-01-06 00:37 UTC, Panquesito7 commented on mods/ctf/ctf_classes/medic.lua
> +		if antisabotage.is_sabotage(pos, minetest.get_node(pos), player) then return end -- Fix paxel being capable of mining blocks under teammates
This mod (or `ctf_classes`) will need to depend on `antisabotage mod`.

2021-01-06 01:13 UTC, Panquesito7 commented on mods/ctf/ctf_classes/medic.lua
> +		if minetest.get_modpath("antisabotage") then
This'll only check if the mod is enabled. That doesn't mean `ctf_classes` depends on this mod.
You must add `antisabotage` in mod dependencies in `ctf_classes` mod, in `mod.conf`.

2021-01-06 01:30 UTC, Panquesito7 commented on mods/pvp/antisabotage/init.lua
> +
```suggestion
```

2021-01-06 01:50 UTC, Panquesito7 requested changes

2021-01-06 01:50 UTC, Panquesito7 commented on mods/ctf/ctf_classes/mod.conf
> +depends = ctf, ctf_flag, ctf_colors, ctf_map_core, ctf_stats, ctf_bandages, physics, shooter, hpregen, give_initial_stuff, dropondie, crafting, sniper_rifles, grenades, furnace, ctf_respawn_immunity,
Wrong.
```suggestion
depends = ctf, ctf_flag, ctf_colors, ctf_map_core, ctf_stats, ctf_bandages, physics, shooter, hpregen, give_initial_stuff, dropondie, crafting, sniper_rifles, grenades, furnace, ctf_respawn_immunity, ctf_marker, ctf_match
optional_depends = antisabotage
```

2021-01-06 02:02 UTC, Panquesito7 commented on mods/pvp/antisabotage/init.lua
> +				for _, item in pairs(minetest.get_node_drops(oldnode)) do -- Properly remove items dropped by nodes, now also protects against possible crash by nodes dropping more than one item.
Make it shorter so it can be more readable for users.
```suggestion
				for _, item in pairs(minetest.get_node_drops(oldnode)) do -- Properly remove items dropped by nodes,
				-- now also protects against possible crash by nodes dropping more than one item.
```

2021-01-06 02:18 UTC, TSafa-23 commented on mods/pvp/antisabotage/init.lua
> +				for _, item in pairs(minetest.get_node_drops(oldnode)) do -- Properly remove items dropped by nodes, now also protects against possible crash by nodes dropping more than one item.
no

2021-01-06 04:14 UTC, LoneWolfHT approved these changes

2021-01-06 04:14 UTC, merged