Bugfix of "Add reason to medkit"
MT-CTF/capturetheflag pull request #734
Opened 2021-01-05 06:12 UTC by Emojigit

Sorry, my PRs have a lot of problems before. here is the list that this PR fix:
 * Fix reasons while attack and damage
 * Remove `die` reason, add `attack` reason

2021-01-05 10:13 UTC, Emojigit commented
@Panquesito7

2021-01-05 17:34 UTC, LoneWolfHT requested changes

2021-01-05 17:34 UTC, LoneWolfHT commented on mods/pvp/medkits/init.lua
> +	end
Trailing whitespace

2021-01-05 18:52 UTC, Panquesito7 commented on mods/pvp/medkits/init.lua
>  	elseif reason == "die" then
I still see die reason?

2021-01-05 23:57 UTC, Emojigit commented on mods/pvp/medkits/init.lua
> +	end
I will add this. But why?

2021-01-06 00:24 UTC, Panquesito7 approved these changes

2021-01-06 00:24 UTC, Panquesito7 commented
Just need to fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/pull/734/checks?check_run_id=1653483292) warnings **before** merge.

2021-01-06 00:28 UTC, Emojigit commented
@Panquesito7 I don't know what does the warning means.
```
mods/pvp/medkits/init.lua:63:5: line contains trailing whitespace
```

2021-01-06 00:33 UTC, Panquesito7 commented on mods/pvp/medkits/init.lua
> +	end
```suggestion
	end
```

2021-01-06 00:36 UTC, Panquesito7 approved these changes
@LoneWolfHT can be merged. 👍

2021-01-06 00:36 UTC, Emojigit commented on mods/pvp/medkits/init.lua
> +	end
@Panquesito7 Resolved

2021-01-06 03:56 UTC, merged