Add "Capture Rate" statistic
MT-CTF/capturetheflag pull request #737
Opened 2021-01-05 22:03 UTC by realOneplustwo

Statistic to show how good a player is at capturing the flag.

2021-01-06 00:39 UTC, Panquesito7 commented on mods/ctf/ctf_stats/chat.lua
> +			"\nCapture rate: " .. math.floor(cr * 100) .. "%" ..
Shouldn't this be like

```diff
- 			"\nCapture rate: " .. math.floor(cr * 100) .. "%" ..
+ 			"\nCapture rate: %" .. math.floor(cr * 100)
```

2021-01-06 01:16 UTC, realOneplustwo reviewed
Should I keep it at math.floor or should I change it to math.round?

2021-01-06 01:17 UTC, realOneplustwo commented on mods/ctf/ctf_stats/chat.lua
> +			"\nCapture rate: " .. math.floor(cr * 100) .. "%" ..
That would make it look like "Capture rate: %100", instead of "Capture rate: 100%", which is what I am going for.

2021-01-06 01:31 UTC, Panquesito7 commented on mods/ctf/ctf_stats/chat.lua
> +			"\nCapture rate: " .. math.floor(cr * 100) .. "%" ..
OH yeah...thought my suggestion was the other way round. 😄

2021-01-06 12:02 UTC, appgurueu commented
> Should I keep it at math.floor or should I change it to math.round?

Lua doesn't have `math.round`, use `math.floor(number + 0.5)` if you want it.

2021-01-25 23:12 UTC, Panquesito7 commented
Can someone re-run the LuaCheck checks?

2021-01-26 23:57 UTC, LoneWolfHT requested changes

2021-01-26 23:57 UTC, LoneWolfHT commented on mods/ctf/ctf_stats/chat.lua
> +      minetest.colorize("#63d437", "Kills: ") ..
This should be double-indented past line 44's indentation (same for the other similar lines)

2021-01-28 01:59 UTC, realOneplustwo commented on mods/ctf/ctf_stats/chat.lua
> +      minetest.colorize("#63d437", "Kills: ") ..
Fixed.

2021-02-04 18:16 UTC, closed without merging