Make treasure chests diggable and drop their contents when dug
MT-CTF/capturetheflag pull request #748
Opened 2021-01-12 22:51 UTC by realOneplustwo

2021-01-18 04:25 UTC, LoneWolfHT commented
This doesn't make treasure chests diggable anymore

2021-01-18 04:31 UTC, LoneWolfHT requested changes
nvm about my last comment, Github being dumb

2021-01-18 04:31 UTC, LoneWolfHT commented on mods/other/tsm_chests/init.lua
> +		for i = 1, inv:get_size("main") do
Pretty sure you can just do
```lua
for k, itemstack in pairs(inv:get_list("main") do```

2021-01-18 04:31 UTC, LoneWolfHT commented on mods/other/tsm_chests/init.lua
> +			inv:set_stack("main", i, nil)
```suggestion
			inv:set_stack("main", i)
```

nil is the value given when an argument isn't passed

2021-03-08 02:36 UTC, Panquesito7 commented on mods/other/tsm_chests/init.lua
> +				_ = obj and obj:set_velocity({x = math.random(-1, 1), y = 5, z = math.random(-1, 1)})
Is this variable even being used? It should be marked as `local` (see [LuaCheck](https://github.com/MT-CTF/capturetheflag/pull/748/checks?check_run_id=2042105702) checks).
```suggestion
				local _ = obj and obj:set_velocity({x = math.random(-1, 1), y = 5, z = math.random(-1, 1)})
```

2021-03-08 20:58 UTC, realOneplustwo commented on mods/other/tsm_chests/init.lua
> +				_ = obj and obj:set_velocity({x = math.random(-1, 1), y = 5, z = math.random(-1, 1)})
I thought underscore was a throwaway variable.

2021-03-08 22:20 UTC, realOneplustwo commented on mods/other/tsm_chests/init.lua
> +				_ = obj and obj:set_velocity({x = math.random(-1, 1), y = 5, z = math.random(-1, 1)})
Anyway, the purpose of line 69 is just to call obj:set_velocity after checking obj is not nil.

2021-11-30 01:15 UTC, closed without merging