Add nodes that affect speed
MT-CTF/capturetheflag pull request #752
Opened 2021-01-15 22:26 UTC by realOneplustwo

1. Sticky cobwebs will both slow you down and almost nullify your ability to jump.
2. Quicksand will slow you down if you walk on it.
3. Asphalt will increase your speed if you walk on it.

2021-01-16 00:22 UTC, TSafa-23 commented on mods/other/speed_nodes/init.lua
> +minetest.register_node("speed_nodes:cobweb", {
```suggestion
local players = {}
minetest.register_node("speed_nodes:cobweb", {
```
IIRC the mod won't work without this, also luacheck hates you because of this missing

2021-01-16 00:24 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +minetest.register_node("speed_nodes:cobweb", {
"players" is from the physics mod

2021-01-16 00:26 UTC, TSafa-23 commented on mods/other/speed_nodes/init.lua
> +minetest.register_node("speed_nodes:cobweb", {
Is it global though?

2021-01-16 00:27 UTC, realOneplustwo commented on mods/other/speed_nodes/init.lua
> +minetest.register_node("speed_nodes:cobweb", {
Yes, I globalized it.

2021-01-17 19:46 UTC, Panquesito7 requested changes
Please fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/pull/752/checks?check_run_id=1712267766) warnings.

2021-01-17 19:59 UTC, realOneplustwo commented
Not necessary. I used a table from another mod (the physics mod), but I did not explicitly define it in my mod, hence LuaCheck starts complaining. But it still works.

2021-01-17 20:04 UTC, Panquesito7 commented
> But it still works

It may work, but we also want the code to be clean and understandable. 🙂

2021-01-17 20:06 UTC, realOneplustwo commented
So should I edit the physics mod as well so that I can add some function to check if an override layer exists?

2021-01-17 20:09 UTC, Panquesito7 commented
> So should I edit the physics mod as well so that I can add some function to check if an override layer exists?

Sounds good to me. 👍

2021-01-18 18:51 UTC, Panquesito7 reviewed
One question: shouldn't the mod `ctf_map_vote` be added in a separate PR?

2021-01-18 18:51 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_vote/init.lua
> +-- code by oneplustwo
If this is your code, then you should provide a `README.md` explaining what the mod does, how does it work, etc.. You also need to add a `LICENSE` file.

2021-01-18 18:51 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_vote/init.lua
> +        if minetest.get_player_by_name(name) == nil then
```suggestion
        if not minetest.get_player_by_name(name) then
```

2021-01-18 18:51 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_vote/init.lua
> +        if minetest.get_player_by_name(name) == nil then
```suggestion
        if not minetest.get_player_by_name(name) then
```

2021-01-18 18:51 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_vote/init.lua
> +        if minetest.get_player_by_name(name) == nil then
```suggestion
        if not minetest.get_player_by_name(name) then
```

2021-01-18 18:51 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_vote/mod.conf
> +depends = ctf_map_core, ctf_stats
```suggestion
depends = ctf_map_core, ctf_stats

```

2021-01-18 19:07 UTC, realOneplustwo commented
I accidentally pushed to the wrong branch, my bad.

2021-01-18 19:07 UTC, closed without merging

2021-01-18 19:44 UTC, Panquesito7 commented
Try not to make new PR's, update the current PR so it'll be easier for others to review it.