Added map voting feature
MT-CTF/capturetheflag pull request #753
Opened 2021-01-18 02:55 UTC by realOneplustwo

Use /upvote to upvote the map.
Use /downvote to downvote the map.
Use /unvote to remove your vote.

Very WIP. Extensive testing needed.

2021-01-18 04:32 UTC, LoneWolfHT commented
Remember to add newlines at the end of your files

2021-01-19 06:46 UTC, JostP commented
Add  [random message](https://github.com/MT-CTF/capturetheflag/blob/2e3ffe8be0ccdc7ffad228604887f2777561a796/mods/other/random_messages/init.lua#L50), so player will know how to vote.

2021-01-21 02:11 UTC, Panquesito7 requested changes
Please fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/runs/1730300632) warnings.

2021-01-21 02:11 UTC, Panquesito7 commented on mods/other/random_messages/init.lua
> +		"Use /rate [rating] to rate the current map on a scale of 1 to 5. If /rate is used alone, it will remove your rating.",
```suggestion
		"Use /rate [rating] to rate the current map on a scale of 1 to 5. If /rate is used without parameters, it will remove your rating.",
```

2021-01-21 02:11 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_rating/init.lua
> +-- code by oneplustwo
Maybe add a `README.md` file explaining what this mod does, and a `LICENSE` file (this is required and extremely recommended).

2021-01-21 02:11 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_rating/mod.conf
> +depends = ctf_map_core, ctf_stats
Maybe add a description saying what the mod does?

2021-01-21 02:56 UTC, realOneplustwo commented on mods/ctf/ctf_map/ctf_map_rating/init.lua
> +-- code by oneplustwo
This isn't a standalone mod though, are you sure it's required?

2021-01-21 21:07 UTC, realOneplustwo commented on mods/ctf/ctf_map/ctf_map_rating/mod.conf
> +depends = ctf_map_core, ctf_stats
Pretty self-explanatory imo.

2021-01-24 01:11 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_map_rating/init.lua
> +-- code by oneplustwo
It is required, all mods should have a license set.

2021-01-24 02:18 UTC, realOneplustwo commented on mods/ctf/ctf_map/ctf_map_rating/init.lua
> +-- code by oneplustwo
But it's part of a modpack.

2021-02-27 13:20 UTC, xenonca commented
Ideally I would love to see the option to rate a map in the maps catalogue, along with what the current map rating is, but I'm aware this is probably even more complicated to implement

2021-03-12 17:33 UTC, xenonca commented on mods/ctf/ctf_map/ctf_map_rating/init.lua
> +-- code by oneplustwo
I don't think it's required either, if not stated otherwise it's licensed under the same license as the game (LGPLv2.1+)

2021-03-13 09:31 UTC, xenonca commented
**Problem:** Type `/rate`, this will return "Rating must be an integer". However then you can't rate a map with an integer cause the rating cooldown is active.

2021-11-30 01:15 UTC, closed without merging