Change stats color when type /r
MT-CTF/capturetheflag pull request #759
Opened 2021-01-21 18:36 UTC by AnyBlue

It separates the stats message from other messages.
![image](https://user-images.githubusercontent.com/69259430/105396073-21c5f200-5c28-11eb-865b-d123f245d474.png)

2021-01-21 18:47 UTC, JostP commented on mods/ctf/ctf_stats/chat.lua
> +                        minetest.colorize("#ffea00", math.floor(stat.score))))))))
Why so many  closing brackets?

2021-01-21 18:49 UTC, AnyBlue commented on mods/ctf/ctf_stats/chat.lua
> +                        minetest.colorize("#ffea00", math.floor(stat.score))))))))
> Why so many closing brackets?

Oh, yeah... It wasn't working for me

2021-01-21 19:04 UTC, Panquesito7 requested changes
Please fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/pull/759/checks?check_run_id=1744107107) warnings.

2021-01-21 19:04 UTC, AnyBlue commented
> Please fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/pull/759/checks?check_run_id=1744107107) warnings.

I know

2021-01-21 19:11 UTC, Panquesito7 commented on mods/ctf/ctf_stats/chat.lua
> +			minetest.colorize("#63d437", "Kills: ") ..
```suggestion
			minetest.colorize("#63d437", "Kills: ") ..
```

2021-01-21 19:11 UTC, Panquesito7 commented on mods/ctf/ctf_stats/chat.lua
> +			minetest.colorize("#63d437", "\nScore: ")) ..
```suggestion
			minetest.colorize("#63d437", "\nScore: ")) ..
```

2021-01-22 13:17 UTC, moreavy approved these changes
Didn't test but the Idea and the screenshot looks good. All Fine 👍🏾

2021-01-23 17:13 UTC, merged