Heal players after they have made a kill
MT-CTF/capturetheflag pull request #766
Opened 2021-01-29 22:47 UTC by realOneplustwo

After killing a player, the killer will be healed by two hearts.

2021-01-29 23:32 UTC, Panquesito7 reviewed
The mod is missing a LICENSE. I recommend using MIT.

2021-01-29 23:32 UTC, Panquesito7 commented on mods/pvp/killheal/init.lua
> +local heal_val = 4 -- two hearts
```suggestion
-- Capture the Flag mod: killheal

local heal_val = 4 -- two hearts
```

2021-01-29 23:32 UTC, Panquesito7 commented on mods/pvp/killheal/README.md
> +# Killheal
```suggestion
# Kill-heal
```

2021-01-29 23:32 UTC, Panquesito7 commented on mods/pvp/killheal/README.md
> +Heals a player after a kill
```suggestion
Heals a player after they kill another player.

## License

Copyright (C) 2021 [oneplustwo](https://github.com/realOneplustwo)
Copyright (C) Various other CTF developers/contributors <!-- Only if the code has been taken from other CTF mods/parts. -->

Kill-heal is licensed under the [MIT](https://mit-license.org/) [license](https://github.com/MT-CTF/capturetheflag/blob/master/mods/pvp/killheal/LICENSE).
```

2021-01-30 02:04 UTC, realOneplustwo commented on mods/pvp/killheal/init.lua
> +local heal_val = 4 -- two hearts
Not necessary, mod.conf and the mod name explains enough.

2021-01-30 02:06 UTC, realOneplustwo commented on mods/pvp/killheal/README.md
> +# Killheal
Nah, I think the original name is better.

2021-01-30 02:19 UTC, realOneplustwo commented on mods/pvp/killheal/README.md
> +Heals a player after a kill
Added License

2021-01-30 02:23 UTC, Panquesito7 commented on mods/pvp/killheal/README.md
> +# License
```suggestion
## License

```

2021-01-30 02:23 UTC, Panquesito7 commented on mods/pvp/killheal/README.md
> +Heals a player after they kill another player
```suggestion
Heals a player after they kill another player.
```

2021-02-09 15:57 UTC, TSafa-23 commented
May conflict with #756

2021-02-10 19:00 UTC, realOneplustwo commented
> May conflict with #756, I suggest implementing a check just in case this happens (or someone nades themselves or something)

There is no check, but there is a minimum function that guarantees that the resulting health will always be the maximum health or lower.

2021-02-11 04:11 UTC, Panquesito7 reviewed
Why remove the license?

2021-02-14 03:18 UTC, Panquesito7 reviewed
Received this error instantly when trying to kill a player:

```
...
2021-02-13 21:16:56: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'killheal' in callback luaentity_Step(): Runtime error from mod 'killheal' in callback on_dieplayer(): ...4\bin\..\games\capturetheflag\mods\pvp\killheal\init.lua:5: bad argument #2 to 'm
2021-02-13 21:16:56: ERROR[Main]: in' (number expected, got nil)
2021-02-13 21:16:56: ERROR[Main]: stack traceback:
2021-02-13 21:16:56: ERROR[Main]: 	[C]: in function 'min'
2021-02-13 21:16:56: ERROR[Main]: 	...4\bin\..\games\capturetheflag\mods\pvp\killheal\init.lua:5: in function <...4\bin\..\games\capturetheflag\mods\pvp\killheal\init.lua:2>
...
```

2021-02-15 00:38 UTC, Panquesito7 approved these changes
Tested; works. 👍
The only thing is when you throw yourself a grenade: it'll show the formspec with the respawn button, when you click on it, you won't be dead because you have two more HP. It also drops your stuff and everything but you're still alive. This should be fixed.

2021-02-15 00:54 UTC, Panquesito7 commented
I don't think this is normal. 😄

https://user-images.githubusercontent.com/51391473/107894642-ddabd180-6ef5-11eb-8059-619c607fbadf.mp4

2021-02-15 00:58 UTC, Panquesito7 commented
> I don't think this is normal. 😄
> 
>  Minetest.5.4.0-1d64e6537-1d64e6537.OpenGL.4.6.14758.2021-02-14.18-52-07.mp4

I even tried this with the player far away, still, that happens? 🤷‍♂️
Weird...the "You're in combat" text appears when that happens.

2021-02-15 01:04 UTC, Panquesito7 commented
When the "You're in a combat" text appears, that means the range of the grenade is passing through the player, but not making any damage, and that's why it heals the player (I think).

https://user-images.githubusercontent.com/51391473/107894985-2fa12700-6ef7-11eb-9353-5b201d1c5471.mp4

2021-02-15 01:58 UTC, LoneWolfHT commented
Grenade damage decreases as you get farther away from the blast site.

2021-02-15 19:24 UTC, realOneplustwo commented
Strange, theoretically killheal should only add health when a player dies.

2021-02-15 19:26 UTC, realOneplustwo commented
A possible theory is that the grenade explosion is actually near enough the player to kill him, but because of killheal, he is brought back to life with the extra hp. If this is true, it will be trivial to fix.

2021-02-18 03:22 UTC, Panquesito7 approved these changes
Tested; works. 👍

2021-02-18 20:21 UTC, appgurueu requested changes
A possible solution, but a fairly arbitrary one; health should IMO not be awarded on kill, but rather on damage ("lifesteal").

2021-02-18 20:21 UTC, appgurueu commented on mods/pvp/killheal/init.lua
> +local heal_val = 4 -- two hearts
Poor naming.

2021-02-18 20:21 UTC, appgurueu commented on mods/pvp/killheal/init.lua
> +    if reason.type == "punch" and minetest.is_player(reason.object) then
Why restrict to punches? I assume shooter has been altered to pretend punches, but is dirty IMO.

2021-02-18 20:21 UTC, appgurueu commented on mods/pvp/killheal/init.lua
> +        if killer == player then return end
Reference check. Due to Minetest player references currently being unique this will work, but I would recommend comparing the names, as the API technically doesn't support this.

2021-02-19 22:24 UTC, realOneplustwo commented on mods/pvp/killheal/init.lua
> +    if reason.type == "punch" and minetest.is_player(reason.object) then
This ensures that the death is always at the hands of another player.

2021-02-19 23:13 UTC, appgurueu commented on mods/pvp/killheal/init.lua
> +    if reason.type == "punch" and minetest.is_player(reason.object) then
> This ensures that the death is always at the hands of another player.

Yes, but why limit to "punch" kills?

2021-02-21 01:39 UTC, Panquesito7 requested changes

2021-02-21 01:39 UTC, Panquesito7 commented on mods/pvp/killheal/init.lua
> +        if killer.get_player_name() == player.get_player_name() then return end
Incorrect; using `.` causes a crash. This fixes it.
```suggestion
        if killer:get_player_name() == player:get_player_name() then return end
```

2021-02-25 19:02 UTC, Panquesito7 approved these changes

2021-03-02 18:54 UTC, realOneplustwo commented
Squashed the commits.

2021-11-30 01:15 UTC, closed without merging