Colorize messages when a player wants to do something behind barrier
MT-CTF/capturetheflag pull request #772
Opened 2021-01-31 16:25 UTC by Toby1710

2021-01-31 16:30 UTC, LoneWolfHT requested changes

2021-01-31 16:30 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
This should be indented two tabs past the start of line 225

2021-01-31 16:30 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
Same for all the other lines

2021-01-31 16:34 UTC, Toby1710 commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
Why?

2021-01-31 17:07 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
That's how our code style works

2021-01-31 17:29 UTC, Toby1710 commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
Can you show how it should be? Maybe suggest changes?

2021-01-31 17:33 UTC, LoneWolfHT commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
```suggestion
			minetest.chat_send_player(name,
					minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
```

2021-02-01 16:19 UTC, TSafa-23 commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +					minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
```suggestion
			minetest.chat_send_player(name, minetest.colorize("#e32d2d", "Can't dig beyond the barrier!"))
```preferable imo

2021-02-01 16:20 UTC, TSafa-23 commented on mods/ctf/ctf_match/buildtime.lua
> +                    minetest.colorize("#e32d2d", "Match hasn't started yet!"))
```suggestion
			minetest.chat_send_player(hitter:get_player_name(), minetest.colorize("#e32d2d", "Match hasn't started yet!"))
```

2021-02-01 16:20 UTC, TSafa-23 commented on mods/ctf/ctf_match/buildtime.lua
> +                minetest.colorize("#e32d2d", "Match hasn't started yet!"))
```suggestion
		minetest.chat_send_player(name, minetest.colorize("#e32d2d", "Match hasn't started yet!"))
```

2021-02-09 14:25 UTC, TSafa-23 requested changes
Green and yellow is not a very good combination, low contrast and do not go together. May I suggest something easier to read and to distinguish? Possibly red

2021-02-11 07:22 UTC, Toby1710 commented
> Green and yellow is not a very good combination, low contrast and do not go together. May I suggest something easier to read and to distinguish? Possibly red

What do you mean?

2021-02-27 13:18 UTC, xenonca commented
This should better be displayed as a HUD message, not in chat.

2021-02-27 18:41 UTC, DiamondPlane commented
> This should better be displayed as a HUD message, not in chat.

It already was in chat so I just colorized it.

2021-03-17 18:06 UTC, xenonca commented
> > This should better be displayed as a HUD message, not in chat.
>
> It already was in chat so I just colorized it.

Added `hud_events` in the meanwhile so you might want to change that now.
Also I think this shouldn't be colorized red. In Minetest a red message is something you usually get when an error ocured, this is not the case here. Changing the color or even leaving it white is fine if it's added as a hud_event IMO

2021-03-17 18:37 UTC, DiamondPlane commented
Ok, that's good that you added "hud_events". 😃
Maybe I'll not colorize it but make it as a hud?

2021-03-18 15:11 UTC, closed without merging