Don't count kill assist on build time or player immunity
MT-CTF/capturetheflag pull request #795
Opened 2021-02-11 13:02 UTC by savilli

Fix https://github.com/MT-CTF/capturetheflag/issues/793
Introduce ctf.register_can_attack callbacks that can stop any ctf related attack logic.

2021-02-11 14:20 UTC, LoneWolfHT requested changes

2021-02-11 14:20 UTC, LoneWolfHT commented on mods/ctf/ctf/teams.lua
> +end
Just create a ctf.can_attack() function. Mods will still be able to add things to it if needed. Will result in clearer code too

2021-02-11 14:34 UTC, savilli commented on mods/ctf/ctf/teams.lua
> +end
>  Mods will still be able to add things to it if needed
How so? What mod should do if it want to reject the damage?

2021-02-11 20:29 UTC, LoneWolfHT commented on mods/ctf/ctf/teams.lua
> +end
```lua
local oldfunc = ctf.can_attack
ctf.can_attack = function()
    -- New code here, can call the old function with oldfunc()
end
```

2021-02-12 11:14 UTC, savilli commented on mods/ctf/ctf/teams.lua
> +end
We already have a common way to register callback using register_ functions. It's used in minetest api as well as in ctf (ctf.register_on_killedplayer, ctf.register_on_punchplayer). Why you want to do it another way? In my view two different ways to register callback will only add confusion and decrease code readability.

2021-02-12 14:37 UTC, LoneWolfHT commented on mods/ctf/ctf/teams.lua
> +end
The register_on() callbacks are used to let mods change behavior of something else. In this case you want a mod to change it's behavior based on what something else says. In a situation like that you use the method I just mentioned.
See minetest.is_protected() for an example. CTF also has a few functions doing the same. Although I forget where exactly they are.

2021-02-12 15:03 UTC, savilli commented on mods/ctf/ctf/teams.lua
> +end
It's absolutely not clear how to distinguish two cases. But minetest.is_protected is a valid case. If you insist on that way I'll do like is_protected.

2021-02-13 22:17 UTC, merged