Add a command to see who is on bounty
MT-CTF/capturetheflag pull request #799
Opened 2021-02-15 12:42 UTC by Toby1710

j45 helped me a bit. (I'm not very good at lua)

2021-02-15 15:48 UTC, JostP requested changes
Something is wrong with code, luacheck has failed. And players who has bounty on his head shouldn't be able to see who is a bounty. Bountied player don't see bounty message on purpose.

2021-02-16 00:49 UTC, Panquesito7 commented
What message should display if the command runner has the bounty?
I think it should be like "No player with a bounty for now".

2021-02-16 00:50 UTC, Panquesito7 commented on mods/ctf/ctf_bounties/init.lua
> +                  if bountied_player then
This will fix the LuaCheck run.
```suggestion
                  if bountied_player then
```

2021-02-16 01:09 UTC, LoneWolfHT commented
> What message should display if the command runner has the bounty?
> I think it should be like "No player with a bounty for now".

'There are no bounties at the moment'

2021-02-16 10:51 UTC, Toby1710 commented
> > What message should display if the command runner has the bounty?
> > I think it should be like "No player with a bounty for now".
> 
> 'There are no bounties at the moment'

👍🏻 Thanks

2021-02-16 10:53 UTC, Toby1710 commented
I forgot to check the Luacheck. Done

2021-02-16 11:11 UTC, Toby1710 commented
> Something is wrong with code, luacheck has failed. And players who has bounty on his head shouldn't be able to see who is a bounty. Bountied player don't see bounty message on purpose.

Why shouldn't players see their bounty?

2021-02-18 03:24 UTC, Panquesito7 commented
> > Something is wrong with the code, luacheck has failed. And players who have a bounty on their head shouldn't be able to see who is a bounty. Bountied players don't see the bounty message on purpose.
> 
> Why shouldn't players see their bounty?

The purpose of the bounty is to be a surprise. So this command shouldn't show the bountied player if there's a bounty or not. Simply tell them that there's no bounty yet.

2021-02-18 13:06 UTC, TSafa-23 commented
Essentially what I did, I recommend testing to make sure it works before doing anything though

2021-02-25 08:50 UTC, DiamondPlane commented
Will make a new PR, I have problem with this.

2021-02-25 08:50 UTC, closed without merging

2021-02-25 08:53 UTC, DiamondPlane commented
I decided to close it.