Limit placement to 5 nodes per second
MT-CTF/capturetheflag pull request #803
Opened 2021-02-18 20:15 UTC by appgurueu

Second try, as I'm still frustrated. Simple solution: Limits node placement to a sane speed. Can be increased to 10 nodes per second if too slow. Won't apply to team doors unless [this fix](https://github.com/MT-CTF/capturetheflag/pull/698/files#diff-3de2a0a8a27905263bcf2f5a3213265e015b7408874b6ed27a307aade5d91ecfR357-R370) is implemented too.

2021-02-18 20:42 UTC, TSafa-23 commented
Moreover curious, does this give you the node back if you can't place it?

2021-02-18 20:45 UTC, Calinou commented
A fast clicker may be able to place 6 nodes or even 7 nodes, so 5 per second might be a bit frustrating.

2021-02-18 21:41 UTC, appgurueu commented
> A fast clicker may be able to place 6 nodes or even 7 nodes in one second, so limiting to 5 nodes per second might be a bit frustrating to those who can click fast enough.

As said, the limit should probably be bumped to 10/7 placements per second.

> Also, there should be a chat message or HUD notification when trying to place nodes too fast.

I haven't come up with a non-spammy way to convey this yet.

2021-02-18 21:59 UTC, appgurueu commented
> Moreover curious, does this give you the node back if you can't place it?

If `on_placenode` is properly executed, yes. Docs say if it returns `true`, the item should not be taken.

2021-02-18 22:00 UTC, LoneWolfHT commented
What's the difference between get_us_time() and os.time()?

2021-02-18 22:46 UTC, Panquesito7 requested changes
The mod is missing a license and a `README.md` file. For the license: I recommend using [MIT](https://mit-license.org/).

2021-02-19 07:50 UTC, appgurueu commented
> What's the difference between get_us_time() and os.time()?

A simple call to `os.time()` will return time with second precision, which is absolutely useless for this application (as multiple places per second should be possible).

2021-02-19 07:52 UTC, appgurueu commented
> The mod is missing a license and a `README.md` file. For the license: I recommend using [MIT](https://mit-license.org/).

Quite bloaty, isn't it?

2021-02-19 15:12 UTC, LoneWolfHT commented
Readme.md isn't required. But a license is a good idea. I always forget that

2021-03-04 08:34 UTC, appgurueu commented
Closes #819

2021-03-04 20:35 UTC, Panquesito7 requested changes
You should provide a `LICENSE.txt` file (see the [MIT](https://mit-license.org) license website).

2021-03-08 11:13 UTC, appgurueu commented
@moreavy note that the specific limitation is still subject to discussion. There should however be some, even if it's quite "liberal" (like 15, 20 or even 30 blocks per second), as otherwise, the client is hardly ratelimited.

2021-03-08 16:34 UTC, moreavy commented
> @moreavy note that the specific limitation is still subject to discussion. There should however be some, even if it's quite "liberal" (like 15, 20 or even 30 blocks per second), as otherwise, block placement is not restricted at all. Hacked clients can abuse this by spamming large cobble structures in the blink of an eye.

I understood that, but try keeping the node placement limits per seconds to be less, so that it won't affect the normal gameplay.

2021-03-27 12:11 UTC, appgurueu commented
This is ready for merge. The poll on Discord has decided for <= 5 blocks per second, which is what this PR implements.

If this turns out to be too restricting, it can be easily tweaked (`init.lua#3`).

2021-03-27 13:54 UTC, Anthony-De commented
Looks good. 👍

2021-03-27 14:27 UTC, merged