Prevent players to throw frag/smoke grenade on build time
MT-CTF/capturetheflag pull request #804
Opened 2021-02-20 10:56 UTC by Toby1710

2021-02-21 01:58 UTC, Panquesito7 commented on mods/pvp/grenades/grenades.lua
> +        end
Wrong indentation.

2021-02-21 01:58 UTC, Panquesito7 commented on mods/pvp/grenades/grenades.lua
> +        end
Same here as above.

2021-02-21 02:02 UTC, Panquesito7 approved these changes
👍 apart from the above (tested).

2021-02-21 13:36 UTC, Toby1710 commented
Hmm... Can you suggest changes me to make the indentation correct, please?

2021-02-21 19:00 UTC, TSafa-23 requested changes
Be sure to fix redundancies/indentation otherwise it likely won't be merged. Also, does this prevent grenades from being thrown or only giving them back if they were thrown before the build time is up?

2021-02-23 09:06 UTC, Toby1710 commented
https://github.com/MT-CTF/capturetheflag/pull/804#discussion_r579849054 @TSafa-23  I tested with this, it gave me error. But on frag it didn't

2021-02-23 12:58 UTC, TSafa-23 commented
Was more of an example because you asked to see one btw, just so you know how it roughly should look

2021-02-24 06:38 UTC, Toby1710 commented
> Was more of an example because you asked to see one btw, just so you know how it roughly should look

Should I leave the code that I did?

2021-02-25 08:59 UTC, DiamondPlane commented
I have a problem with this PR, I'll create a new one.

2021-02-25 08:59 UTC, closed without merging