Prevent players to throw frag/smoke grenade on build time
MT-CTF/capturetheflag pull request #812
Opened 2021-02-25 09:03 UTC by DiamondPlane

I made a new one because https://github.com/MT-CTF/capturetheflag/pull/804#issuecomment-785733553

2021-05-11 20:25 UTC, LoneWolfHT requested changes
This needs to use tabs instead of spaces

2021-05-11 20:25 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +            minetest.chat_send_player(name, "Match hasn't started yet!")
This is never called because of the return statement above it

2021-05-11 20:25 UTC, LoneWolfHT commented on mods/pvp/grenades/grenades.lua
> +            minetest.chat_send_player(pname, "Match hasn't started yet!")
This is never called because of the return statement above it

2021-05-12 13:31 UTC, DiamondPlane commented on mods/pvp/grenades/grenades.lua
> +            minetest.chat_send_player(pname, "Match hasn't started yet!")
Can't edit

2021-06-27 17:17 UTC, closed without merging