New award system: use submodules
MT-CTF/capturetheflag pull request #818
Opened 2021-03-02 11:52 UTC by Emojigit

Close #17 
Close #735 
A replacement of #735 , using submodule to import awards and rebase

2021-03-03 00:03 UTC, Panquesito7 reviewed
You should probably add a license to the `ctf_awards` mod. I recommend using [MIT](https://mit-license.org/).

2021-03-03 00:04 UTC, Emojigit commented
> You should probably add a license to the `ctf_awards` mod. I recommend using [MIT](https://mit-license.org/).

Why I cannot use LGPL?

2021-03-03 00:22 UTC, Panquesito7 commented
> cannot use LGPL?

I was just recommending using [MIT](https://mit-license.org), but you can use LGPLv2.1+ too.
I recommend using [MIT](https://mit-license.org) as it is simple, short, and easy to understand.

2021-03-03 01:23 UTC, Emojigit commented
> > cannot use LGPL?
> 
> I was just recommending using [MIT](https://mit-license.org), but you can use LGPLv2.1+ too.
> I recommend using [MIT](https://mit-license.org) as it is simple, short, and easy to understand.

The MIT license can close source, but LGPL cannot. so I will use LGPL.

2021-03-03 01:34 UTC, Emojigit commented
Ready to merge

2021-03-04 10:42 UTC, moreavy approved these changes
Luacheck also working :+1:

2021-03-04 20:33 UTC, Panquesito7 commented on mods/ctf/ctf_awards/lgpl-2.1.txt
> +                  GNU LESSER GENERAL PUBLIC LICENSE
This file should be named `LICENSE.txt`.

2021-03-04 23:17 UTC, Emojigit commented on mods/ctf/ctf_awards/lgpl-2.1.txt
> +                  GNU LESSER GENERAL PUBLIC LICENSE
@Panquesito7 I did these changes:
 - Use LGPL's markdown version (easier reading on GitHub)
 - Create README
 - Merge license notice into README
 - Rename lgpl-2.1.txt to LICENSE.md

2021-03-05 00:58 UTC, Panquesito7 commented on mods/ctf/ctf_awards/README.md
> +A mod that add awards to Minetest Capture The Flag
```suggestion
## ctf_awards

A mod that adds awards to Minetest Capture The Flag

```

2021-03-05 04:28 UTC, Emojigit commented on mods/ctf/ctf_awards/README.md
> +A mod that add awards to Minetest Capture The Flag
@Panquesito7 committed suggestion

2021-03-05 04:42 UTC, Panquesito7 reviewed
You should probably add the awards mentioned in https://github.com/MT-CTF/capturetheflag/issues/17#issuecomment-438737639.

2021-03-05 04:45 UTC, Emojigit commented
> You should probably add the awards mentioned in [#17 (comment)](https://github.com/MT-CTF/capturetheflag/issues/17#issuecomment-438737639).

I have a problem: How to get is the player holding the flag before dies?

2021-03-05 06:51 UTC, Panquesito7 commented
> How to get if the player is holding the flag

This function may help.
https://github.com/MT-CTF/capturetheflag/blob/a51d7cd347fe80e81465aa93f1b6ce2d056b291e/mods/ctf/ctf_flag/api.lua#L53-L61

2021-03-06 00:36 UTC, Emojigit commented
> > How to get if the player is holding the flag
> 
> This function may help.
> 
> https://github.com/MT-CTF/capturetheflag/blob/a51d7cd347fe80e81465aa93f1b6ce2d056b291e/mods/ctf/ctf_flag/api.lua#L53-L61

I think this is useless. CTF engine put down player's flag on player die.

2021-03-09 07:27 UTC, moreavy commented
@Emojigit you should use the MIT license because the whole Capture The Flag game is made in the MIT license, even the award system. You can't change the license directly without discussing it with the Admins.

2021-03-12 01:54 UTC, Emojigit commented
> @Emojigit you should use the MIT license because the whole Capture The Flag game is made in the MIT license, even the award system. You can't change the license directly without discussing it with the Admins unless its your own mod.

Oh my god! I will change it soon.

2021-03-12 03:55 UTC, Panquesito7 commented
> I will change it soon.

Not sure if it's legal to change from LGPLv2.1+ to MIT.
I'm not a lawyer, though; you should ask a lawyer about this.

2021-03-12 05:05 UTC, moreavy commented
@Emojigit The license of the Awards mod in the GitLab repository it `MIT`. However you can't change the license without the authority or permission of the author i.e. Rubenwardy. Please see that you aren't messing up with the license and keeping it same as it was.

2021-03-12 05:07 UTC, moreavy commented on mods/ctf/ctf_awards/README.md
> +    Copyright © 2020-2021 Cato Yiu
The mod is made by Rebenwardy, so please don't change the name to yours.

2021-03-12 05:24 UTC, LoneWolfHT commented
They can relicense it if they want to since they're the author and none of the contributors mind.

I looks like this code adds a submodule and a new mod that registers awards with it btw @moreavy

2021-03-12 05:36 UTC, moreavy commented
> They can relicense it if they want to since they're the author and none of the contributors mind.
> 
> I looks like this code adds a submodule and a new mod that registers awards with it btw @moreavy

If its a new mod, then surely they can changes the license.

2021-03-18 10:30 UTC, Emojigit commented on mods/ctf/ctf_awards/README.md
> +    Copyright © 2020-2021 Cato Yiu
> @Emojigit The license of the Awards mod in the GitLab repository it `MIT`. However you can't change the license without the authority or permission of the author i.e. Rubenwardy. Please see that you aren't messing up with the license and keeping it same as it was.

@moreavy Remove LGPL license is not possible, so I will release it under both MIT and LGPL.

2021-03-18 10:31 UTC, Emojigit commented on mods/ctf/ctf_awards/README.md
> +    Copyright © 2020-2021 Cato Yiu
> The mod is made by Rebenwardy, so please don't change the name to yours.

This mod is a standalone mod that uses the award API, not add some code to the original award mod.

2021-03-18 16:25 UTC, LoneWolfHT commented on mods/ctf/ctf_awards/README.md
> +    Copyright © 2020-2021 Cato Yiu
@Emojigit Pick LGPL or MIT and go with that. LGPL is fine but MIT makes life easier.
I don't think you need to worry about not being able to switch out of LGPL with a project this small. Especially since this hasn't been merged yet

2021-03-19 03:23 UTC, moreavy reviewed
The code and the awards look good, I just doubt the `gravitation` award, else everything looks fine. @Emojigit can you explain the value of the gravitation award?

2021-03-19 03:32 UTC, Emojigit commented
> The code and the awards look good, I just doubt the `gravitation` award, else everything looks fine. @Emojigit can you explain the value of the gravitation award?

Just for fun. I don't know what awards can I make before, so I made this.

2021-03-19 03:35 UTC, moreavy commented
> > The code and the awards look good, I just doubt the `gravitation` award, else everything looks fine. @Emojigit can you explain the value of the gravitation award?
> 
> Just for fun. I don't know what awards can I make before, so I made this.

You mean that there isn't any use of that award?

2021-03-19 06:17 UTC, moreavy commented
You should remove the awards which doesn't make sense.

2021-03-19 08:08 UTC, moreavy commented
```lua
awards.register_award("canary", {
  title = "Canary",
  description = "be the first to die in a match",
  icon = "heart.png",
  difficulty = 1,
})
```
I don't think this is makes sense.

2021-03-19 08:09 UTC, Emojigit commented
> 
> I don't think this is makes sense.

why?

2021-03-19 08:09 UTC, Emojigit commented
> ```lua
> awards.register_award("canary", {
>   title = "Canary",
>   description = "be the first to die in a match",
>   icon = "heart.png",
>   difficulty = 1,
> })
> ```
> 
> I don't think this is makes sense.

This is suggested by @rubenwardy at #17

2021-03-19 08:11 UTC, Emojigit commented
> Well, why yo give an award if someone dies 1st in a match? Also unlocking it would be really easy.

You have to ask rubenwardy.

2021-03-19 08:14 UTC, moreavy commented
That's a low priority issue. Also it was just suggested, not applied.

2021-03-31 04:49 UTC, Panquesito7 requested changes
Multi-licensing? That's going to be kind of messy. You should probably stick with MIT, as mentioned before. Also, I'm not sure if that is how [multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing) works.

2021-03-31 05:54 UTC, moreavy commented
You get the gravitation award whenever you die due to falldamage, I don't think it is necessary to have this award. Aldo even rubenwardy didn't suggest this award.

2021-11-30 01:15 UTC, closed without merging