Add hud_events
MT-CTF/capturetheflag pull request #825
Opened 2021-03-10 20:56 UTC by xenonca

Reuses the HUD API created in `hud_scores` to provide a base to solve #642 by adding HUD messages

2021-03-10 21:32 UTC, Panquesito7 requested changes
You should add a license to this mod. I recommend using [MIT](https://mit-license.org).

2021-03-10 21:38 UTC, xenonca commented
# How to test
Replace some spammy chat messages (like mentioned in the linked issue above) with HUD messages and see if it works.
## Example
Replace [this](https://github.com/MT-CTF/capturetheflag/blob/30e9ac02fb3282366a67e853c986fef24d2cfcd9/mods/ctf/ctf_bandages/init.lua#L36) line with the following code:
```lua
hud_event.new(pname, {
	name = "ctf_bandages:heal",
	color = "0xC1FF44",
	value = name .. " has healed you!"
})
```
Let someone heal you and look for the HUD message that should appear. (Should look something like this:)
![image](https://user-images.githubusercontent.com/36995016/110701298-4a627500-81f1-11eb-999a-ca3b9a915e27.png)

2021-03-10 21:38 UTC, xenonca commented
> You should add a license to this mod. I recommend using [MIT](https://mit-license.org).

Please look at the Readme :P

2021-03-11 00:37 UTC, Panquesito7 commented on mods/other/hud_events/README.md
> +Changes that have been made compared to the original `hud_score` mod. Lines mentioned underneath refer to the lines in the `hud_events`' init.lua file.
```suggestion
Changes that have been made compared to the original `hud_score` mod. The lines mentioned underneath refer to the lines in the `init.lua` file.  
```

2021-03-11 07:49 UTC, xenonca commented on mods/other/hud_events/README.md
> +Changes that have been made compared to the original `hud_score` mod. Lines mentioned underneath refer to the lines in the `hud_events`' init.lua file.
I'm explicitly mentioning that the lines refer to the hud_events mod because one could think I mean the ones in hud_score

2021-03-12 16:24 UTC, RyanZem reviewed
Nice, it won't spam the chat now. This works fine, I hope this will be merged to CTF :)

2021-03-12 16:29 UTC, merged