Prevent players to spam with empty messages in team chat
MT-CTF/capturetheflag pull request #830
Opened 2021-03-16 11:29 UTC by DiamondPlane

2021-03-16 18:32 UTC, Panquesito7 commented on mods/ctf/ctf_chat/init.lua
> +			end
```suggestion
			if param == "" then
			    minetest.chat_send_player(name, "You did not write anything, see /help t")
			end
```

2021-03-17 17:56 UTC, xenonca requested changes

2021-03-17 17:56 UTC, xenonca commented on mods/ctf/ctf_chat/init.lua
> +
```suggestion
```
This will still send a message into the team chat. Instead add this to line 250:
```
if param == "" then
	return false, "-!- Empty team message, see /help t"
end
```

2021-03-17 18:38 UTC, DiamondPlane commented on mods/ctf/ctf_chat/init.lua
> +
@xenonca Really? I checked and it didn't.

2021-03-18 08:17 UTC, DiamondPlane commented on mods/ctf/ctf_chat/init.lua
> +
Edited! Thanks

2021-03-18 22:30 UTC, Panquesito7 commented on mods/ctf/ctf_chat/init.lua
> +			end
Please adjust your code here.
```suggestion
			if param == "" then
		        return false, "-!- Empty team message, see /help t"
			end
```

2021-03-27 11:01 UTC, xenonca commented on mods/ctf/ctf_chat/init.lua
> +
I think you need to insert that code in line 250, else you'll be logging empty team messages without a reason.

2021-03-27 11:03 UTC, xenonca commented on mods/ctf/ctf_chat/init.lua
> +
> I think you need to insert that code in line 250, else you'll be logging empty team messages without a reason.

:point_up:

2021-03-27 11:03 UTC, xenonca commented
I think you need to insert that code in line 250, else you'll be logging empty team messages without a reason.

2021-03-31 04:45 UTC, Panquesito7 approved these changes

2021-04-02 15:54 UTC, xenonca approved these changes

2021-04-21 15:46 UTC, merged