Make barrier fail messages as hud
MT-CTF/capturetheflag pull request #834
Opened 2021-03-18 15:17 UTC by DiamondPlane

2021-03-21 08:57 UTC, xenonca commented
Need to add `hud_events` to the mods dependencies I think

2021-03-21 14:15 UTC, DiamondPlane commented
> Need to add `hud_events` to the mods dependencies I think
Yes

2021-03-27 10:57 UTC, xenonca requested changes

2021-03-27 10:57 UTC, xenonca commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +			name = "ctf_map:barrier",
```suggestion
			name = "ctf_map:barrier_dig",
```

2021-03-27 10:57 UTC, xenonca commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +			value = "Can't dig or place node beyond barrier!"
```suggestion
			value = "Can't dig or place nodes beyond the barrier!"
```

2021-03-27 10:57 UTC, xenonca commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +					name = "ctf_map:barrier",
```suggestion
					name = "ctf_map:barrier_buildtime",
```

2021-03-27 15:15 UTC, DiamondPlane commented on mods/ctf/ctf_map/ctf_map_core/barrier.lua
> +			value = "Can't dig or place node beyond barrier!"
That's a good idea

2021-06-27 17:12 UTC, closed without merging