Sprint gets reset to full on new game
MT-CTF/capturetheflag pull request #841
Opened 2021-03-23 21:30 UTC by Minetest-j45

im not sure what the difference is between ```ctf_match.register_on_new_match(function())``` and ```ctf.register_on_new_game(function())``` so im not sure which i need to use(feel free to make suggestions if you know) but if this works, then great

2021-03-23 21:41 UTC, Panquesito7 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
```suggestion
		player[player:get_player_name()].stamina = STAMINA_MAX
```

2021-03-23 21:41 UTC, Panquesito7 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
```suggestion
		player[player:get_player_name()].stamina = STAMINA_MAX
```

2021-03-23 21:47 UTC, Minetest-j45 commented
wait what... no? im confused

2021-03-23 21:49 UTC, Minetest-j45 commented
see line 119, how they reset it on respawn... it is ```players[player:get_player_name()].stamina```, not ```player[player:get_player_name()].stamina```

2021-03-23 21:54 UTC, Panquesito7 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
Where is the variable/parameter `players` defined?

2021-03-23 21:54 UTC, Panquesito7 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
Same here.

2021-03-23 22:00 UTC, Minetest-j45 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
line 22

2021-03-23 22:00 UTC, Minetest-j45 commented on mods/other/sprint/init.lua
> +		players[player:get_player_name()].stamina = STAMINA_MAX
same answer as above

2021-03-24 19:31 UTC, appgurueu commented
Two things:
1. Is `register_on_new_game` needed? Why is `register_on_new_match` insufficient?
2. If both are needed, make your function - which is the same for both - a named local one and pass the same function to both instead of copying & pasting

2021-03-24 19:44 UTC, Minetest-j45 commented
See my first comment i made, when i opened this, as i said... I dont know the difference between them so i out both. If you know, feel free to change my pr

2021-03-24 23:21 UTC, Anthony-De commented
@Minetest-j45 
`register_on_new_game` only ever used on server start.
You only need to use `register_on_new_match`.

2021-03-24 23:31 UTC, Anthony-De requested changes

2021-03-24 23:31 UTC, Anthony-De commented on mods/other/sprint/init.lua
> +end)
```suggestion
minetest.after(0, function()
	ctf_match.register_on_new_match(function()
		for _, player in pairs(players) do
			player.stamina = STAMINA_MAX
		end
	end)
end)
```

2021-03-25 00:26 UTC, Anthony-De commented
There is a little issue, the hudbar doesn't update till the player starts sprinting.

2021-03-25 00:55 UTC, Panquesito7 commented
> update till the player starts sprinting

That should be fixed in another PR, I think.

2021-03-25 08:55 UTC, appgurueu commented on mods/other/sprint/init.lua
> +end)
`minetest.after(0, ...)` should not be used, use `minetest.register_on_mods_loaded(...)` instead. Why is it needed here?

2021-03-25 12:13 UTC, Anthony-De commented on mods/other/sprint/init.lua
> +end)
Because ctf_match isn't defined when this file runs.

2021-03-25 19:34 UTC, Minetest-j45 commented
is this (with AnthonyDE's changes) ready to merge?

2021-03-28 16:16 UTC, Minetest-j45 commented
oops. i accidentally closed this PR and didnt notice

2021-03-30 23:48 UTC, Panquesito7 approved these changes

2021-06-06 13:29 UTC, closed without merging