Disable Towering While Fighting
MT-CTF/capturetheflag pull request #890
Opened 2021-05-24 04:36 UTC by air-glitch

I am `disco-dancer` in-game. I would just like to disable towering while fighting because many noobs tower up when I am killing them.

2021-05-24 11:16 UTC, moreavy approved these changes
Test: Working, Great Job :+1:

2021-05-24 19:24 UTC, appgurueu commented
1. This belongs in the place_limit mod IMO
2. Do not call remove node, but set the old node instead. Have a look at how `place_limit` does it. Also, `return true` for the node to not be wasted.

2021-05-26 07:02 UTC, moreavy commented
This code disables towering while fighting, but actually, it also disable blocking the way in tunnels too while it shouldn't.

2021-05-26 07:33 UTC, air-glitch commented
May I know on which axis (`x`, `y` or `z`) do people tower up?

2021-05-26 08:07 UTC, appgurueu commented
> May I know on which axis (`x`, `y` or `z`) do people tower up?

y, of course?

2021-05-31 07:53 UTC, appgurueu requested changes

2021-05-31 07:53 UTC, appgurueu commented on mods/pvp/anticoward/init.lua
> +	if no_towering[placer:get_player_name()] and (placer:get_pos().y = (pos.y + 1)) then
Syntax error, I assumed you intended `==`? Anways, this won't work as expected; you'd have to do a range check for that.

2021-06-01 05:30 UTC, air-glitch commented on mods/pvp/anticoward/init.lua
> +	if no_towering[placer:get_player_name()] and (placer:get_pos().y = (pos.y + 1)) then
I've already fixed `==` bug.

2021-06-02 04:06 UTC, moreavy commented
> > May I know on which axis (`x`, `y` or `z`) do people tower up?
> 
> y, of course?

Wrong, `z` axis is the one where players tower up.

2021-06-02 04:07 UTC, moreavy commented on mods/pvp/anticoward/init.lua
> +	if no_towering[placer:get_player_name()] and (placer:get_pos().y == (pos.y + 1)) then
```suggestion
	if no_towering[placer:get_player_name()] and (placer:get_pos().z == pos.z) then
``` I think this should work.

2021-06-02 04:23 UTC, moreavy commented on mods/pvp/anticoward/init.lua
> +	if no_towering[placer:get_player_name()] and (placer:get_pos().y == (pos.y + 1)) then
```suggestion
	if no_towering[placer:get_player_name()] and ((math.floor(placer:get_pos().y) == (pos.y + 1)) or (math.ceil(player:get_pos().y) == (pos.y + 1)) then
```

2021-11-30 01:15 UTC, closed without merging