Add antiwalkthrough mod
MT-CTF/capturetheflag pull request #901
Opened 2021-06-19 10:11 UTC by appgurueu

This prevents players from freely glitching through blocks.

2021-06-29 05:50 UTC, DiamondPlane commented
It works good but I think teammates can trap teammates, like if you can't dig that node or don't have a pickaxe.

2021-06-29 12:27 UTC, appgurueu commented
> It works good but I think teammates can trap teammates, like if you can't dig that node or don't have a pickaxe.

Well I could disable placing blocks where teammates - excluding the placer - stand.

2021-08-06 16:43 UTC, Panquesito7 requested changes
Maybe provide a `README.md` file explaining what the mod does and a license file, too.

2021-08-06 16:43 UTC, Panquesito7 commented on mods/pvp/antiwalkthrough/init.lua
> +minetest.register_entity(":__builtin:item", def)
Missing an endline. This could cause problems with some OS'ses and IDEs.

```suggestion
minetest.register_entity(":__builtin:item", def)
```

2021-11-30 01:15 UTC, closed without merging

2021-11-30 12:56 UTC, appgurueu commented
This could have been merged into v3 perfectly fine.

2021-11-30 13:39 UTC, savilli commented
We have decided we don't need that

2021-11-30 16:18 UTC, appgurueu commented
> We have decided we don't need that


Who are "we"?