add leave message
MT-CTF/capturetheflag pull request #909
Opened 2021-07-04 03:28 UTC by ksandronline

Add colorize nickname in leave message.

p.s. its my first request in game - please do full check me.

2021-07-04 18:20 UTC, Panquesito7 requested changes
I suggest the mod's name be changed to `colorized_leave_messages`.

2021-07-04 18:20 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +end
This would make the code shorter. There's no need to register another function; you can simply override the `core.send_leave_message` function.
```suggestion
function core.send_leave_message(player_name, timed_out)
	local player = ctf.player(player_name)
	local tcolor = ctf_colors.get_color(player).css

	local announcement = "*** " ..  minetest.colorize(tcolor, player_name) .. " left the game."
	if timed_out then
		announcement = announcement .. " (timed out)"
	end
	minetest.chat_send_all(announcement)
end
```

2021-07-04 18:20 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +core.register_on_leaveplayer(function(player, timed_out)
```suggestion
minetest.register_on_leaveplayer(function(player, timed_out)
```

2021-07-04 18:20 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +end)
```suggestion
end)

```

2021-07-04 18:20 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/mod.conf
> +author = ksandr
I'm not really sure if this useful. IIRC, the `author` field is only used for CDB packages.

2021-07-04 18:59 UTC, ksandronline commented on mods/ctf/ctf_leave_message/mod.conf
> +author = ksandr
okay delete field author. (im copy mod.conf from any mod and edit.) im copy all.

2021-07-04 19:18 UTC, ksandronline commented
I did a test - it didn't work for me after the change. It doesn't work right now.

2021-07-04 19:19 UTC, Panquesito7 requested changes

2021-07-04 19:19 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/mod.conf
> +author = ksandr
```suggestion
description = Colorizes leaving messages

```

2021-07-04 19:35 UTC, Panquesito7 requested changes

2021-07-04 19:35 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +	ctf.send_leave_message(player_name, timed_out)
This will fix the error you're experiencing.
```suggestion
	core.send_leave_message(player_name, timed_out)
```

2021-07-04 19:44 UTC, Panquesito7 commented
Does it work properly now?

2021-07-04 19:49 UTC, ksandronline commented
> Does it work properly now?
The error has disappeared. But now the message appears twice.

2021-07-04 20:21 UTC, Panquesito7 reviewed
This should fix the message appearing twice.

2021-07-04 20:21 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +end)
There's no need to run this callback anymore, as Minetest itself should already run it. Here, we just want to override the function.
```suggestion
```

2021-07-04 20:35 UTC, ksandronline commented
yes, everything is working correctly now.

2021-07-04 20:36 UTC, Panquesito7 approved these changes
Looks good. Thanks. 👍
@LoneWolfHT, this PR can be merged.

2021-07-04 23:07 UTC, LoneWolfHT requested changes

2021-07-04 23:07 UTC, LoneWolfHT commented on mods/ctf/ctf_leave_message/init.lua
> +function core.send_leave_message(player_name, timed_out)
```suggestion
function minetest.send_leave_message(player_name, timed_out)
```

2021-07-04 23:22 UTC, Panquesito7 commented on mods/ctf/ctf_leave_message/init.lua
> +function core.send_leave_message(player_name, timed_out)
Do you think that would override the function correctly?

2021-07-05 05:43 UTC, ksandronline commented
in think this style programmer CTF.

2021-07-05 20:53 UTC, LoneWolfHT commented on mods/ctf/ctf_leave_message/init.lua
> +function core.send_leave_message(player_name, timed_out)
`minetest.` should be used wherever possible. `minetest.send_leave_message()` is listed in the lua_api.txt so it should work fine.

2021-07-05 20:54 UTC, merged