Add traps
MT-CTF/capturetheflag pull request #968
Opened 2021-12-20 04:38 UTC by olliy1or

2021-12-20 04:39 UTC, Panquesito7 requested changes

2021-12-20 04:39 UTC, Panquesito7 commented on mods/ctf/ctf_map/ctf_traps.lua
> +})
Missing an endline.
```suggestion
})

```

2021-12-20 15:17 UTC, RyanZem approved these changes

2021-12-28 20:27 UTC, LoneWolfHT requested changes
Textures don't follow naming conventions

2022-01-05 23:51 UTC, LoneWolfHT requested changes
This should only add the crafts to `classic` and `nade_fight`

2022-01-05 23:53 UTC, LoneWolfHT approved these changes
Just realized the crafts aren't added to any modes by this code, I can do that after this is merged.

2022-01-06 00:08 UTC, savilli commented on mods/ctf/ctf_modebase/crafting.lua
> +-- Traps
You don't need `type = "inv"` and `level = 1` anymore

2022-01-06 20:02 UTC, merged