Add snipere
MT-CTF/capturetheflag pull request #969
Opened 2021-12-21 12:49 UTC by olliy1or

2021-12-21 20:03 UTC, Panquesito7 approved these changes

2022-01-01 15:49 UTC, savilli requested changes

2022-01-01 15:49 UTC, savilli commented on mods/ctf/ctf_combat/ctf_ranged/init.lua
> +			scoped[name] = nil
You can't modify the map while iterating

2022-01-01 15:49 UTC, savilli commented on mods/ctf/ctf_combat/ctf_ranged/init.lua
> +local timer = 0.2
I think 0.2 is too low. 1 second is fine.

2022-01-06 22:28 UTC, savilli commented on mods/ctf/ctf_combat/ctf_ranged/init.lua
> +			scoped[name] = nil
No

2022-01-06 22:28 UTC, savilli commented on mods/ctf/ctf_combat/ctf_ranged/init.lua
> +	if scoped[player:get_player_name()] then
You can do just
```lua
scoped[player:get_player_name()] = nil
```

2022-01-11 08:13 UTC, savilli commented
LGTM

2022-01-24 21:43 UTC, merged