Mark opened chests as opened
MT-CTF/capturetheflag pull request #985
Opened 2022-02-04 20:51 UTC by xenonca

Make it visible for your teammates when a chest has already been opened by someone.
AFAIK it is not ([yet](https://github.com/minetest/minetest/issues/3528)) possible to change node textures during run time, this is why I'm using `minetest.swap_node()`.

2022-02-04 21:02 UTC, LoneWolfHT commented
How are opened chests handled in MTG?

2022-02-04 21:16 UTC, savilli commented
> How are opened chests handled in MTG?

The same approach
https://github.com/minetest/minetest_game/blob/42baede13fdf855773cc44ce10f4a3ea4e239404/mods/default/chests.lua#L134

2022-02-04 21:17 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +	light_source = 1,
Why?

2022-02-04 21:19 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +minetest.register_node("ctf_map:chest", {
I'm afraid you need to copy the whole spec, or a closed chest would be diggable, and you could put items inside.

2022-02-04 21:36 UTC, xenonca commented on mods/ctf/ctf_map/nodes.lua
> +	light_source = 1,
Better distinction in the dark
![grafik](https://user-images.githubusercontent.com/36995016/152606312-91ffd73c-6252-4ed2-9d4a-a6963b9c1c9f.png)

2022-02-04 21:39 UTC, xenonca commented
> How are opened chests handled in MTG?
I think I should have been more clear with the explanation, what I mean is that visited chests, chests that have already been touched/opened by a player, will be distinguishable from untouched ones.

2022-02-04 21:41 UTC, xenonca commented on mods/ctf/ctf_map/nodes.lua
> +minetest.register_node("ctf_map:chest", {
From what I've tested they are not diggable, not sure how you'd be able to put items inside, the node changes instantly at right-click, is there another way to access the chest?

2022-02-04 22:05 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +minetest.register_node("ctf_map:chest", {
I think you can do it with modified client, I wouldn't risk.

2022-02-04 22:05 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +minetest.register_node("ctf_map:chest", {
Looks like `can_dig` does nothing and can be removed.

2022-02-06 16:59 UTC, appgurueu commented
Looks like massive code duplication to me; shouldn't this basically be the same def. as the treasure chest? Why don't you `table.copy` the treasure chest def. then?

2022-02-13 11:50 UTC, savilli requested changes

2022-02-13 11:50 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +	allow_metadata_inventory_put = function(pos, listname, index, stack, player)
Plz no, too much copy-paste. Look how MTG does and do the same https://github.com/minetest/minetest_game/blob/42baede13fdf855773cc44ce10f4a3ea4e239404/mods/default/chests.lua#L241

2022-08-03 12:10 UTC, savilli approved these changes
LGTM

2022-08-03 12:17 UTC, appgurueu commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("formspec", chest_formspec)
Couldn't you avoid duplicating this code by calling the original on_construct here?

2022-08-03 12:18 UTC, appgurueu commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("infotext", "Treasure Chest (visited)")
Is duplicating this here even necessary? `swap_node` won't call `on_construct` or `on_destruct`; the previous chest meta will be preserved anyways.

2022-08-03 12:28 UTC, savilli commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("infotext", "Treasure Chest (visited)")
What if you want to place a visited chest manually?

2022-08-03 15:10 UTC, appgurueu commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("infotext", "Treasure Chest (visited)")
Why would you want that?

2022-08-13 18:17 UTC, xenonca commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("infotext", "Treasure Chest (visited)")
I assume you don't (at least I couldn't think of any situation where you'd want that).

2022-08-14 18:02 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +		meta:set_string("infotext", chestv)
```suggestion
		minetest.get_meta(pos):set_string("infotext", chestv)
```

No need for a local here unless you're planning to reuse it.

2022-08-14 18:04 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +		minetest.swap_node(pos, {name="ctf_map:chest_opened"})
```suggestion
		minetest.swap_node(pos, { name = "ctf_map:chest_opened" })
```

Sry for being pedantic, but better to fix codestyle here itself. :)

2022-08-14 18:05 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +"default_chest_front.png^[colorize:#000000:50^[crack:1:1:1"}
```suggestion
ochest_def.tiles = {
	"default_chest_top.png^[colorize:#000000:50^[crack:1:1:1",
	"default_chest_top.png^[colorize:#000000:50^[crack:1:1:1",
	"default_chest_side.png^[colorize:#000000:50^[crack:1:1:1",
	"default_chest_side.png^[colorize:#000000:50^[crack:1:1:1",
	"default_chest_side.png^[colorize:#000000:50^[crack:1:1:1",
	"default_chest_front.png^[colorize:#000000:50^[crack:1:1:1"}
```

2022-08-14 18:06 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
What does this do? 👀

2022-08-14 18:36 UTC, appgurueu commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
It makes the chest glow.

2022-08-14 19:00 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
That much I figured. I was wondering about the *why* part. :)

2022-08-14 19:54 UTC, appgurueu commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
To "highlight" the chest

2022-08-14 21:15 UTC, xenonca commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
In fact it makes visited chests glow _less_ than the ones which haven't been opened yet.

2022-08-15 03:45 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
> In fact it makes visited chests glow _less_ than the ones which haven't been opened yet.

Ah so unopened chests glow even more. Didn't know that.

2022-08-15 03:47 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
> In fact it makes visited chests glow _less_ than the ones which haven't been opened yet.

So where's the code that makes unopened chests glow more?

2022-08-16 10:36 UTC, xenonca commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
https://github.com/MT-CTF/capturetheflag/blob/54cb7a6f67d64f07e68389a22159cf8f1c8a6045/mods/ctf/ctf_map/nodes.lua#L143

2022-08-16 10:43 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +	meta:set_string("infotext", "Treasure Chest (visited)")
Is this resolved now?

2022-08-16 10:43 UTC, magnetar47 commented on mods/ctf/ctf_map/nodes.lua
> +ochest_def.light_source = 1
Oh I missed it. Thanks.

2022-10-11 18:34 UTC, merged